### PR TITLE
pkg/trace: make pkg/trace/agent control the lifecycle of pkg timing

### LINKED ISSUE #22030: [BUG] pkg/trace/metrics/timing is leaking a goroutine
**Agent Environment**

N/A

**Describe what happened:**
While working on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30438, [`goleak`](https://github.com/uber-go/goleak) detected a leaking `goroutine`. This is happening due to an indirect dependency on the [timing package.](https://pkg.go.dev/github.com/datadog/datadog-agent@v0.0.0-20200429180151-914b7646d5d4/pkg/trace/metrics/timing)

Here's the output of `goleak`:
```
 Goroutine 70 in state select, with github.com/DataDog/datadog-agent/pkg/trace/metrics/timing.(*Set).Autoreport.func1 on top of the stack:
github.com/DataDog/datadog-agent/pkg/trace/metrics/timing.(*Set).Autoreport.func1()
        /Users/crobert/go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/trace@v0.50.2/metrics/timing/timing.go:59 +0xed
created by github.com/DataDog/datadog-agent/pkg/trace/metrics/timing.(*Set).Autoreport in goroutine 1
        /Users/crobert/go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/trace@v0.50.2/metrics/timing/timing.go:54 +0x96
```

**Describe what you expected:**
No leaking `goroutines`. The impact here is leaked memory usage upon shutdown. Since this is happens when `timing` is an indirect dependency there's no access to `timing.Stop()`.

**Steps to reproduce the issue:**
import "github.com/DataDog/datadog-agent/pkg/trace/agent"

**Additional environment details (Operating System, Cloud provider, etc):**
Related to #13934
[Here's a more in-depth explanation](https://github.com/census-instrumentation/opencensus-go/issues/1191#issuecomment-1332707024) around an identical issue that is in OpenCensus.

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

Revamp the timing package and make pkg/trace/agent control its lifecycle. Inject the dogstatsd client as a dependency of `timing` instead of importing the `metrics` package directly, this simplifies the refactor and eases testing.

### Motivation

fixes https://github.com/DataDog/datadog-agent/issues/22030

### Describe how to test/QA your changes

Checked the metrics submitted using the `timing` package haven't regressed.

image

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

File: pkg/trace/agent/agent.go [hunk 1]
```diff
@@ -218,6 +219,7 @@ func (a *Agent) loop() {
 	} {
 		stopper.Stop()
 	}
+	timing.Stop()
```
Comment (knusbaum) [inline pkg/trace/agent/agent.go:222]: Do we want to defer this instead?

File: pkg/trace/metrics/client.go [hunk 2]
```diff
@@ -20,12 +21,23 @@ type StatsClient interface {
...
 
+var m sync.Mutex
+
+// SetClient sets the global Statsd client.
+func SetClient(client StatsClient) {
+	m.Lock()
+	defer m.Unlock()
+	Client = client
+}
+
```
Comment (knusbaum) [inline pkg/trace/metrics/client.go:32]: An atomic would be more efficient, since (i think) we're just protecting the `Client` reference itself.

File: pkg/trace/metrics/timing/timing.go [hunk 3]
```diff
@@ -15,75 +15,102 @@ import (
...
+	m.Lock()
+	defer m.Unlock()
+	if defaultSet == nil {
+		log.Error("Timing hasn't been initialized, trace-agent metrics will be missing")
+		return
+	}
+	defaultSet.Since(name, start)
+}
+
+var m = sync.Mutex{}
```
Comment (knusbaum) [inline pkg/trace/metrics/timing/timing.go:41]: We should probably use an atomic here to avoid a double-lock (lock `m`, lock `defaultSet.mu`)

**Review by knusbaum — COMMENTED** [review]
Some initial comments

File: pkg/trace/agent/agent.go (hunk 1 above)
Comment (ahmed-mez) [reply pkg/trace/agent/agent.go:222]: Can do! I put here in the `loop()` method near the stoppers for consistency but can use a defer in `Run` instead since `Run` is blocking.

File: pkg/trace/metrics/client.go (hunk 2 above)
Comment (ahmed-mez) [reply pkg/trace/metrics/client.go:32]: Do you mean [atomic.Value](https://pkg.go.dev/sync/atomic#Value) ?

**Comment by ahmed-mez** [comment]
@knusbaum thanks! I ended up implementing a different and simpler approach.

**Review by ajgajg1134 — APPROVED** [review]
