### PR TITLE
Set proper timeout and polling period for the apiserver

### LINKED ISSUE #1870: Agent v6 puts the kubernetes API server under a lot of pressure on a cluster with many pods
**Describe what happened:**
We're running a ~100-node kubernetes cluster which we've been monitoring with Datadog. We recently upgraded from agent v5 to agent v6, which fixed a couple of reporting issues we had been having.

A couple of days later we noticed that our lead master node was using a _lot_ more CPU than it had previously been using. On further investigation, we also found that our etcd cluster was serving a huge amount of extra network traffic (we jumped from ~70MiB/min of data output up to ~880MiB/min, concentrated on a single etcd box). All the CPU load on this master node was focused on the Kubernetes API server.

Long story short, we ended up isolating the v6 datadog agent as the cause of the increased API load. Removing it caused all our symptoms to disappear immediately.

**Describe what you expected:**
We expected the upgrade to agent v6 not to cause additional pressure on our API server.

**Steps to reproduce the issue:**
I'm not sure how reproducable this issue is on a smaller cluster. We're running 180-odd pods in our biggest namespace (which is the only one we're currently monitoring with Datadog).

**Additional environment details (Operating System, Cloud provider, etc):**
We're running Kubernetes on Ubuntu in AWS. I'm happy to provide more details on our setup if required.

### PR DESCRIPTION
**Pull request by JulienBalestra**
### What does this PR do?

Honor the configuration option instead of using a constant.
I also added a configurable timeout for the apiserver requests.

### Motivation

Fix #1870

### CODE REVIEW

File: pkg/util/kubernetes/apiserver/apiserver.go [hunk 1]
```diff
@@ -315,7 +314,7 @@ func (c *APIClient) checkResourcesAuth() error {
 
 // ComponentStatuses returns the component status list from the APIServer
 func (c *APIClient) ComponentStatuses() (*v1.ComponentStatusList, error) {
-	return c.Cl.CoreV1().ComponentStatuses().List(metav1.ListOptions{TimeoutSeconds: &globalTimeoutSeconds})
+	return c.Cl.CoreV1().ComponentStatuses().List(metav1.ListOptions{TimeoutSeconds: &c.timeoutSeconds})
```
Comment (devonboyer) [inline pkg/util/kubernetes/apiserver/apiserver.go]: The `timeoutSeconds` is being used here for more than just the required calls for metadata mapping but the config option is call `kubernetes_metadata_tag_client_timeout`. 

Can we name this something more generic like `kubernetes_apiserver_client_timeout`?

Not a big deal so I'll leave this up to you.

Comment (JulienBalestra) [reply pkg/util/kubernetes/apiserver/apiserver.go]: You're right it's way better

**Review by mfpierre — APPROVED** [review]
