### PR TITLE
pkg/trace/writer: added limiting retries on failed payloads

### LINKED ISSUE #6960: pkg/trace: no useful logs upon retries to send payloads
When failing to send tracing payloads to Datadog, `tracing-agent` only logs useful information at DEBUG level.

I had a trailing newline character in my API key by mistake, which prevented `tracing-agent` from sending anything to Datadog (filed #6961 to have the API key sanitized), but the logs said nothing until I read the code and realized I should change the log level. [This](https://github.com/DataDog/datadog-agent/blob/0424948ecdf99450fa153e200877cb8c35475d0b/pkg/trace/writer/sender.go#L252) is where the call reporting a retry is made, and [this](https://github.com/DataDog/datadog-agent/blob/0424948ecdf99450fa153e200877cb8c35475d0b/pkg/trace/writer/trace.go#L244-L246) is where it's processed.

It would be great if the agent logged at least sampled errors at warning level.

### PR DESCRIPTION
**Pull request by dianashevchenko**
Closes #6960.  There were no useful logs upon retries to send payloads, so the payloads were sent multiple times with no warning until they were pushed out of queue. Now each retry happens with a warning and can be retried up to 5 times, then dropped

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details that should be tested during the QA.

### CODE REVIEW

File: pkg/trace/writer/sender.go [hunk 1]
```diff
@@ -247,6 +250,14 @@ func (s *sender) sendPayload(p *payload) {
...
 		}
 		atomic.AddInt32(&s.attempt, 1)
+		atomic.AddInt32(&p.retries, 1)
+
+		if atomic.LoadInt32(&p.retries) > maxRetries {
+			//exceeded max retries per payload, dropping payload
+			log.Error("Exceeded max retries per payload, dropping payload ")
+			s.releasePayload(p, eventTypeDropped, stats)
+			return
+		}
```
Comment (knusbaum) [inline pkg/trace/writer/sender.go:260]: We should consider how long it takes to reach `maxRetries`. 
It looks like the payload goes right back into the queue when it fails. If the backend is offline even for a minute, we will end up dropping payloads. We should probably hang onto them as long as we can and just let them fall out of the queue when it fills up.

Changing the `Debugf` to a `Warnf` in `pkg/trace/writer/trace.go` solves the initial issue that things get retried indefinitely with silent logs. If we're going to warn on every retry, we don't need to even count retries.

Instead, we might want to keep the `Debugf` and only start emitting `Warnf` here after `s.attempt` exceeds `maxRetries`. Otherwise, intermittent retries showing up as warnings in the logs might alarm users. We should probably only warn when it's a persistent problem. We already have debug logging if they want to see every retry.

That log change should go along with adding `log.Warnf`'s whenever we release a failed payload, like when we fail to send to the queue because the channel is full:
```
		select {
		case s.queue <- p:
			// ** Check s.attempt here **
			s.recordEvent(eventTypeRetry, stats)
			return
		default:
			// ** We should log here, including the err **
			// queue is full; since this is the oldest payload, we drop it
			s.releasePayload(p, eventTypeDropped, stats)
		}
```
And also in the default branch when it's an unknown error.
```
	default:
		// ** Same here **
		// this is a fatal error, we have to drop this payload
		s.releasePayload(p, eventTypeRejected, stats)
```

That way we are
* warning whenever we are retrying sends repeatedly
* warning whenever we drop payloads

**Review by knusbaum — DISMISSED** [review]

File: pkg/trace/writer/sender.go [hunk 2]
```diff
@@ -62,6 +62,9 @@ type eventRecorder interface {
 	recordEvent(t eventType, data *eventData)
 }
 
+//maximum retries for a payload
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:65]: Please note that there needs to be a space after `//` in inline comments.

File: pkg/trace/writer/sender.go [hunk 3]
```diff
@@ -247,6 +250,14 @@ func (s *sender) sendPayload(p *payload) {
 			return
 		}
 		atomic.AddInt32(&s.attempt, 1)
+		atomic.AddInt32(&p.retries, 1)
+
+		if atomic.LoadInt32(&p.retries) > maxRetries {
+			//exceeded max retries per payload, dropping payload
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:256]: Same here and everywhere please 🙏 Also, this line is very obvious and does not require any additional comments for explaining.

File: pkg/trace/writer/sender.go [hunk 4]
```diff
@@ -347,6 +359,7 @@ var ppool = &sync.Pool{
 		return &payload{
 			body:    &bytes.Buffer{},
 			headers: make(map[string]string),
+			retries: 0,
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:362]: When something is at its zero-value (in this case `0` for `int32`), it doesn't need to be specified in the struct definition. You can remove this line.

File: pkg/trace/writer/sender.go [hunk 5]
```diff
@@ -247,6 +250,14 @@ func (s *sender) sendPayload(p *payload) {
 			return
 		}
 		atomic.AddInt32(&s.attempt, 1)
+		atomic.AddInt32(&p.retries, 1)
+
+		if atomic.LoadInt32(&p.retries) > maxRetries {
+			//exceeded max retries per payload, dropping payload
+			log.Error("Exceeded max retries per payload, dropping payload ")
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:257]:
```suggestion
			log.Error("Exceeded max retries per payload, dropping payload.")
```

**Review by gbbr — COMMENTED** [review]
Just a few nits

**Comment by dianashevchenko** [comment]
Last week, Jan 29th, it was resolved that it's better to:
- limit the payload drop only when it's pushed out of the queue as the oldest
- log warnings when overall retries count per sender hits `maxRetries` 

So, at the moment those changes are not up to date, I'll update

File: pkg/trace/writer/sender.go (hunk 1 above)
Comment (dianashevchenko) [reply pkg/trace/writer/sender.go:260]: There is no need to add warnings in the places you mentioned since they already exist one level deeper - in `recordEvent` function that's invoked later in `releasePayload`

File: pkg/trace/writer/sender.go [hunk 6]
```diff
@@ -62,6 +62,9 @@ type eventRecorder interface {
 	recordEvent(t eventType, data *eventData)
 }
 
+//maxRetries specifies max number of failed sends per a sender
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:65]: We need a space after `//` just like the other comments.

File: pkg/trace/writer/sender.go [hunk 7]
```diff
@@ -247,6 +250,10 @@ func (s *sender) sendPayload(p *payload) {
 			return
 		}
 		atomic.AddInt32(&s.attempt, 1)
+
+		if atomic.LoadInt32(&s.attempt) >= maxRetries {
+			log.Warnf("Reached maximum number of retries; error: %s", err.Error())
+		}
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:256]: The terminology here is slightly misleading. When we say "maximum retries", it usually means that we give up after having reached that value. Here however it's simply a threshold for a warning. So let's use different wording. Perhaps `retryWarnThreshold` instead of `maxRetries`?

```suggestion
		if atomic.AddInt32(&s.attempt)%retryWarningThreshold == 0 {
			log.Warnf("Retried payload %d times, got error: %s", s.attempt, err.Error())
		}
```

Notice that I've replace `LoadInt32` with `AddInt32`. There is no need to add, and then load, since [AddInt32](https://golang.org/pkg/sync/atomic/#AddInt32) returns the new value. Also, it might be better to log the warning every Nth retry, not just N, so I changed to a module. I'd suggest setting the value to `3` instead of `5`.

**Review by gbbr — CHANGES_REQUESTED** [review]
Left a few more guidelines. We will have to write a test for this too. We want to make sure it works and solves the customer issue.

File: pkg/trace/writer/sender.go (hunk 7 above)
Comment (dianashevchenko) [reply pkg/trace/writer/sender.go:256]: Yes, the naming fits better. 
The only thing - since `s.attempt` specifies an overall count of failed sends - not per payload - so maybe we should warn that we have a number of different consecutive failed payloads. 

Also, since when a payload goes through, `s.attempt` is swapped with itself divided by two until these values are the same, which might diminish chances of getting those warnings through if we stick to modulo 🤔

Comment (gbbr) [reply pkg/trace/writer/sender.go:256]: > The only thing - since s.attempt specifies an overall count of failed sends - not per payload

Ah yes, you're right! Good catch. I missed that. I guess our interest is to log when a specific payload has been retried multiple times.

The question comes - is this not going to be overkill? Should we instead just change the log level from Debug to Warning?

Comment (gbbr) [reply pkg/trace/writer/sender.go:256]: The only alternative I see is to add a field to the `payload` type called `retries` and use that.

File: pkg/trace/writer/sender.go [hunk 8]
```diff
@@ -339,6 +352,7 @@ func (s *sender) do(req *http.Request) error {
 type payload struct {
 	body    *bytes.Buffer     // request body
 	headers map[string]string // request headers
+	retry   int32
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:355]:
```suggestion
	retries   int32 // number of retries sending this payload
```
Think this is how you had it initially and it made more sense.

File: pkg/trace/writer/sender_test.go [hunk 9]
```diff
@@ -330,3 +330,24 @@ func (r *mockRecorder) recordEvent(t eventType, data *eventData) {
...
+		{3, false},
+		{4, true},
+		{5, false},
+		{6, false},
+		{8, true},
+	} {
+		actual := shouldWarnRetry(test.retries)
+		if actual != test.shouldWarn {
+			t.Fail()
+			t.Logf("expected: %t, actual: %t", test.shouldWarn, actual)
```
Comment (gbbr) [inline pkg/trace/writer/sender_test.go:350]: You can put this on one line with `t.Fatalf`

File: pkg/trace/writer/sender.go [hunk 10]
```diff
@@ -272,6 +276,15 @@ func (s *sender) sendPayload(p *payload) {
 	}
 }
 
+// shouldWarnRetry determines whether a warning should be emitted
+// with the given count of retries to avoid spam
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:280]:
```suggestion
// shouldWarnRetry determines whether a warning should be emitted
// after it has been retried n times.
```
It's nice to try and use the actual argument name in the documentation. It is a bit more friendly and I noticed that's how most repositories do it, including the standard library.

Also, I think in this case `n` makes more sense than `r` as a count.

File: pkg/trace/writer/sender.go [hunk 11]
```diff
@@ -247,6 +247,10 @@ func (s *sender) sendPayload(p *payload) {
 			return
 		}
 		atomic.AddInt32(&s.attempt, 1)
+
+		if r := atomic.AddInt32(&p.retry, 1); shouldWarnRetry(r) {
+			log.Warnf("Retried payload %d times, got error: %s", r, err.Error())
```
Comment (gbbr) [inline pkg/trace/writer/sender.go:252]:
```suggestion
			log.Warnf("Retried payload %d times: %s", r, err.Error())
```
Maybe this is nicer?

**Review by gbbr — COMMENTED** [review]
Awesome! Thanks. A few nits.

**Review by gbbr — APPROVED** [review]
Really nice! Thanks!

⚠️ Note that we are in code freeze. So no merging until that's over.

**Comment by sgnn7** [comment]
@gbbr / @dianashevchenko Master is unfrozen as of today I believe :)

**Review by gbbr — CHANGES_REQUESTED** [review]
We forgot one thing! Almost fell through the cracks. In `newPayload` we need to add:
```go
p.retries = 0
```
Otherwise getting a new payload from the pool might come up with a non-zero value and that'll be confusing and potentially freaky if it ever shows up in a log message.

**Review by gbbr — APPROVED** [review]
