### PR TITLE
[AMLII-2125] Update log source status when replaced

### LINKED ISSUE #30241: [BUG] Incorrect source status upon replacement of a source in a tailer
When a `LogSource` gets replaced in a `Tailer`, the new `LogSource`'s `LogStatus` gets stuck in `IsPending`. This is presented to users in the output of `agent check`, which causes confusion.

The only place where `LogSource` is replaced is [here](
https://github.com/DataDog/datadog-agent/blob/b77289c264adb96c736ce399b56bf4e608905ad8/pkg/logs/launchers/file/launcher.go#L288-L290).
The only place where the `LogSource` status is updated is [in Tailer.Start](https://github.com/DataDog/datadog-agent/blob/b77289c264adb96c736ce399b56bf4e608905ad8/pkg/logs/tailers/file/tailer.go#L236).

Here's an example of what `agent check` displays in such cases (note the `Status: Pending` line):
```
  post--qa/post--post-jobalerts-cmhqa-cb666445c-fnnxq/main
  --------------------------------------------------------
    - Type: file
      Identifier: ac2e1ebc8c3f8c17a113fc57dc865d94ffb78d0f4cb06716d3356620aa6c5657
      Path: /var/log/pods/post--qa_post--post-jobalerts-cmhqa-cb666445c-fnnxq_caaa42a2-74bb-42f4-8f58-30b398a2e15f/main/*.log
      Service: postdaemon
      Source: java
      Status: Pending
        1 files tailed out of 1 files matching  
      Bytes Read: 297770   
      Pipeline Latency:
        Average Latency (ms): 0
        24h Average Latency (ms): 0
        Peak Latency (ms): 0
        24h Peak Latency (ms): 0
```

### PR DESCRIPTION
**Pull request by rayz**
### What does this PR do?
Fixes a bug where when a log source is replaced, the new source status shows `pending` even though it is able to correctly read logs. This is due to the source status having a default `pending` value, and it only being set to `Success` when `Start()` is called on the tailer.

### Motivation
Fix confusion where the status is showing `pending` even though everything is working fine.

### Describe how to test/QA your changes
1. Have 2 custom integrations tail the same file to trigger a source replacement.
2. Run `agent status`. The status show OK for the updated source.
3. Send logs and make sure everything works as normal.

### CODE REVIEW

File: pkg/logs/sources/replaceable_source.go [hunk 1]
```diff
@@ -33,6 +33,7 @@ func (r *ReplaceableSource) Replace(source *LogSource) {
 	r.Lock()
 	defer r.Unlock()
 	r.source = source
+	r.source.Status.Success()
```
Comment (gh123man) [inline pkg/logs/sources/replaceable_source.go:36]: Should we instead be setting the new source status to the same as the old source status? 

ex: 
```
newSource.Status = r.source.Status
r.source = newSource
```
What if the old source had failed for some reason, and then the source gets replaced.

**Review by gh123man — APPROVED** [review]
