### PR TITLE
fix(uprobes): Reduce noisy logging in uprobe attacher

### LINKED ISSUE #38198: [BUG] SYS-PROBE | WARN | (pkg/ebpf/uprobes/attacher.go:632 in handleProcessStart) | could not attach to process
**Agent Environment**
```
$ kubectl exec -it datadog-agent-xq2hj -- agent version
Defaulted container "agent" out of: agent, trace-agent, process-agent, system-probe, init-volume (init), init-config (init), seccomp-setup (init)
Agent 7.67.0 - Commit: bdf863ccc9 - Serialization version: v5.0.150 - Go version: go1.23.9
```

**Describe what happened:**
We upgraded the Agent from `7.66.1` to `7.67.0`
These kind of warnings started appearing in our agent logs:
```
2025-06-24 14:49:16 UTC | SYS-PROBE | WARN | (pkg/ebpf/uprobes/attacher.go:632 in handleProcessStart) | could not attach to process 661472: unexpected error: stat /host/proc/661472/root/runc: no such file or directory
```

**Describe what you expected:**
No new warnings after upgrading.

**Steps to reproduce the issue:**
Upgrade the DD Agent from `7.66.1` to `7.67.0.`

**Additional environment details (Operating System, Cloud provider, etc):**

- Amazon Linux 2023 - EKS optimised.
- EKS 1.32
- Datadog Helm Chart 3.119.0

### PR DESCRIPTION
**Pull request by mbertrone**
### What does this PR do?
This pull request introduces two changes to reduce log noise originating from the eBPF uprobe attacher:
- Adds a Log Limiter: A rate limiter is added to the handleLibraryOpen and handleProcessStart functions in the UprobeAttacher. This prevents floods of warnings when the agent tries to attach probes to very short-lived processes, which is a common and usually benign race condition.
- Disables Detailed Logging: The EnableDetailedLogging flag is explicitly set to false for the USM/TLS uprobe attacher configuration. This prevents verbose debug logs, which are not intended for production, from being enabled.

### Motivation
In environments with high process churn the system-probe can generate a large volume of warnings

### Describe how you validated your changes
- code compiles
- existing tests are passing correctly

### Additional Notes
https://datadoghq.atlassian.net/browse/EBPF-756
https://datadoghq.atlassian.net/browse/EBPF-757

Fixes https://github.com/DataDog/datadog-agent/issues/38198

### CODE REVIEW

**Review by guyarb — APPROVED** [review]

File: pkg/ebpf/uprobes/attacher.go [hunk 1]
```diff
@@ -629,7 +633,9 @@ func (ua *UprobeAttacher) shouldLogRegistryError(err error) bool {
 func (ua *UprobeAttacher) handleProcessStart(pid uint32) {
 	err := ua.AttachPIDWithOptions(pid, false) // Do not try to attach to libraries on process start, it hasn't loaded them yet
 	if ua.shouldLogRegistryError(err) {
-		log.Warnf("could not attach to process %d: %v", pid, err)
+		if ua.attachLimiter.ShouldLog() {
```
Comment (brycekahle) [inline pkg/ebpf/uprobes/attacher.go]: Should we be checking `attachLimiter` inside of `shouldLogRegistryError` instead?

File: pkg/ebpf/uprobes/attacher.go [hunk 2]
```diff
@@ -629,7 +633,9 @@ func (ua *UprobeAttacher) shouldLogRegistryError(err error) bool {
...
+			log.Warnf("could not attach to process %d: %v", pid, err)
```
Comment (brycekahle) [inline pkg/ebpf/uprobes/attacher.go]: I'm wondering about the value of these logs at all? If you are debugging a specific process, and they are limited, then you might miss the log anyways.

File: pkg/ebpf/uprobes/attacher.go (hunk 1 above)
Comment (mbertrone) [reply pkg/ebpf/uprobes/attacher.go]: Good point. Addressed.

File: pkg/ebpf/uprobes/attacher.go (hunk 2 above)
Comment (mbertrone) [reply pkg/ebpf/uprobes/attacher.go]: Great point. If I understood correctly, your concern is about the usefulness of those logs when part of the data is missing. For that use case, the `EnableDetailedLogging` flag should address the issue.

By the way, the flag is currently explicitly set to false and is not exposed in the agent configuration. I can open a separate PR to expose it, if that would be helpful.

**Review by val06 — APPROVED** [review]

File: pkg/ebpf/uprobes/attacher.go (hunk 2 above)
Comment (brycekahle) [reply pkg/ebpf/uprobes/attacher.go]: if `EnableDetailedLogging` is set, it will still rate limit the logs, correct?

Comment (mbertrone) [reply pkg/ebpf/uprobes/attacher.go]: if `EnableDetailedLogging` is set, it bypasses any filtering and rate limiting logic, and prints all the logs.

https://github.com/DataDog/datadog-agent/blob/mbertrone/fix/uprobe-libcrypto-loglimiter/pkg/ebpf/uprobes/attacher.go#L623

**Review by brycekahle — APPROVED** [review]
