### PR TITLE
[packaging/RPM] Write systemd service files to /usr/lib/systemd/system

### LINKED ISSUE #1706: systemd problem on install
**Describe what happened:**
I've noticed that on Centos 7.4 and 7.5(maybe others too) systemd cant find .service file
.service file is located here `/lib/systemd/system/datadog-agent.service`
so I move it to `/usr/lib/systemd/system/datadog-agent.service` and everything works as expected

**Describe what you expected:**
service path should be `/usr/lib/...`

**Steps to reproduce the issue:**
- add datadog repo `https://yum.datadoghq.com/stable/6/x86_64/`
- install datadog
- try to run systemctl start datadog-agent

**Additional environment details (Operating System, Cloud provider, etc):**
on DigitalOcean Centos 7.4+
and manual installed Centos 7.5

### PR DESCRIPTION
**Pull request by olivielpeau**
### What does this PR do?

Writes systemd service files to `/usr/lib/systemd/system` instead of `/lib/systemd/system`.

### Motivation

Recommended by the RHEL/SUSE docs, and [Agent 5 uses these recommended paths too](https://github.com/DataDog/dd-agent-omnibus/blob/5.22.3/config/software/datadog-agent.rb#L47-L59).

Both paths should work on most environments, but we got a report in https://github.com/DataDog/datadog-agent/issues/1706 of the `/lib` path not working. Let's just follow the official docs' recommendations. Fixes #1706.

### CODE REVIEW

File: omnibus/config/projects/agent.rb [hunk 1]
```diff
@@ -157,9 +157,13 @@
   extra_package_file '/etc/init/datadog-agent.conf'
   extra_package_file '/etc/init/datadog-agent-process.conf'
   extra_package_file '/etc/init/datadog-agent-trace.conf'
-  extra_package_file '/lib/systemd/system/datadog-agent.service'
-  extra_package_file '/lib/systemd/system/datadog-agent-process.service'
-  extra_package_file '/lib/systemd/system/datadog-agent-trace.service'
+  systemd_directory = "/usr/lib/systemd/system"
+  if debian?
```
Comment (hush-hush) [inline omnibus/config/projects/agent.rb]: Will this cover ubuntu too ?

**Review by hush-hush — APPROVED** [review]
Small question, looks good otherwise

**Comment by olivielpeau** [comment]
Double-checked running the install and upgrade from 6.2.0 on the resulting RPM works well. Merging
