### PR TITLE
Fix the Agent build on Freebsd

### LINKED ISSUE #1467: Build on FreeBSD 11
Hello, I am trying to build the agent v6 for FreeBSD 11, from source. The environment has the following configuration:

FreeBSD 11.0-RELEASE-p15 with the following ports / libs installed:
go-1.10 (from ports)
python27-2.7.14_1 (from ports)
invoke 0.22.1 (installed via pip)

The last step from the README.md, "invoke agent.build --build-exclude=snmp", triggers the following error:
```
# github.com/DataDog/datadog-agent/pkg/metadata/v5
pkg/metadata/v5/payload_other.go:16:2: undefined: ExternalHostPayload
# github.com/DataDog/datadog-agent/vendor/github.com/DataDog/gohai/platform
vendor/github.com/DataDog/gohai/platform/platform_common.go:33:22: undefined: getArchInfo
```

edit: fixed Markdown

### PR DESCRIPTION
**Pull request by masci**
### What does this PR do?

Fixes #1467 

### Motivation

Recently changes to the metadata payloads broke the build for platforms not supporting Gohai

### CODE REVIEW

File: pkg/status/status.go [hunk 1]
```diff
@@ -44,7 +43,7 @@ func GetStatus() (map[string]interface{}, error) {
 	stats["config"] = getPartialConfig()
 	stats["conf_file"] = config.Datadog.ConfigFileUsed()
 
-	platformPayload, err := new(platform.Platform).Collect()
+	platformPayload, err := getPlatformPayload()
```
Comment (olivielpeau) [inline pkg/status/status.go]: does the rest of the code correctly handle the `nil`value for `platformPayload`? Found this usage in a template which would break I think: https://github.com/DataDog/datadog-agent/blob/6.0.3/pkg/status/dist/templates/header.tmpl#L7 , may want to add a condition on `.platform` there

**Review by olivielpeau — DISMISSED** [review]
left a comment, other than that LGTM!

File: pkg/status/status.go (hunk 1 above)
Comment (masci) [reply pkg/status/status.go]: Changed the return value to an empty map instead of `nil`. The default behaviour is `platform.SomethingMissing` printing `<no value>`. This would break if we instantiate the template passing the option `missingkey=error`, see https://golang.org/pkg/text/template/#Template.Option but I think it's better to assume we're using the right option instead of putting the "gohai missing case" behind an `if` statement in every template using it.

**Review by olivielpeau — APPROVED** [review]
LGTM!
