### PR TITLE
[Logs]: Autodiscovery - Pod Annotation fix

### LINKED ISSUE #2267: Kubernetes Logs with AutoDiscovery doesn't work without ContainerCollectAll config
**Describe what happened:**

When trying to configure logs aggregation on a K8s cluster using pod annotations, the datadog agent won't consume the annotated pods unless the global `logsConfigContainerCollectAll` config option is configured.

**Describe what you expected:**

I would expect to avoid collecting logs from all containers and use annotated pods to consume logs from pods I'm interested by only.
Reading the agent codebase I found the place where the config is required: https://github.com/DataDog/datadog-agent/blob/59d94018c188dc238914a788b7b9663ed45c137d/pkg/logs/input/container/scanner.go#L20-L23

**Steps to reproduce the issue:**

Using datadog helm chart with values:

```
datadog.apiKey=xxx
datadog.apmEnabled=true
datadog.logsConfigContainerCollectAll=true
datadog.logsEnabled=true
datadog.nonLocalTraffic=true
datadog.logLevel=WARN
```

and pod annotation:

```
ad.datadoghq.com/foo.logs=[{"source": "ruby", "service": "foo"}]
```

**Additional environment details (Operating System, Cloud provider, etc):**

```
$ kubectl version --short
Client Version: v1.11.1
Server Version: v1.10.5-gke.4
$ helm version --short
Client: v2.10.0+g9ad53aa
Server: v2.10.0+g9ad53aa
```

Helm version is `1.0.4` https://github.com/helm/charts/tree/master/stable/datadog

### PR DESCRIPTION
**Pull request by ajacquemot**
### What does this PR do?

Fix a bug that would lead a pod annotation config not to be taken into account when `logs_config.container_collect_all` is enabled.

### Motivation

Be able to override logs attributes with pod annotation ad identifier

### Additional Notes

Need to merge this first https://github.com/DataDog/datadog-agent/pull/2277
This should fix https://github.com/DataDog/datadog-agent/issues/2267

### CODE REVIEW

File: pkg/logs/input/docker/ad_identifier_kubelet.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+	}
+	kubeutil, err := kubelet.GetKubeUtil()
+	if err != nil {
+		return false
+	}
+	pod, err := kubeutil.GetPodForEntityID(c.service.GetEntityID())
+	if err != nil {
+		return false
+	}
+	for _, container := range pod.Status.Containers {
```
Comment (tmichelet) [inline pkg/logs/input/docker/ad_identifier_kubelet.go]: why do we loop over pod's containers, instead of using `c`? worth an explanation

**Review by tmichelet — APPROVED** [review]
