### PR TITLE
admissioncontroller:  Prepend injected env vars

### LINKED ISSUE #12820: Admission controller should prepend env vars (rather than append)
**Describe what happened:**
I cannot reference env vars that are injected by the admission controller using kubernetes [dependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/) because they are [appended](https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/admission/mutate/common.go#L69) to the *end* of the env list.  This kind of dependency reference is order-dependent.

**Describe what you expected:**
I can reference env vars that are injected using dependent environment variables, because they are *prepended* to the list, and thus available to env vars created on my pod spec.

**Steps to reproduce the issue:**
* Set up the admission controller.  
* Set up a pod with correct labels to trigger injection of DD_SERVICE per Unified Service Tagging.  e.g.:
```
labels:
    ...
    tags.datadoghq.com/service: my-service-name
```
* Observe that `DD_SERVICE` is correctly set to `my-service-name` at the end of the list of `env` vars for the pod.
* Attempt to set an `env` referencing it:
```
env:
        - name: SOME_DERIVED_ENV_VAR
          value: "$(DD_SERVICE)-preprod"
```
* read the value of `SOME_DERIVED_ENV_VAR` from the pod
* observe that it is literally `"$(DD_SERVICE)-preprod"`
  * we would expect based on the k8s documentation linked above that it should resolve to `my-service-name-preprod` if the declaration of `DD_SERVICE` in the `env` list preceded the reference to it.

This should be a one line change from `append` to reorder it as a prepend in [`common.go`](https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/admission/mutate/common.go#L69)

**Additional environment details (Operating System, Cloud provider, etc):**
kube 1.21 in eks

### PR DESCRIPTION
**Pull request by jcogilvie**
### What does this PR do?
Prepend injected env vars to containers' env lists instead of appending, so DD vars can be referenced using k8s dependent env vars.

### Motivation
Fixes #12820

### Possible Drawbacks / Trade-offs

* datadog injected env vars, by appearing first in the list, can now no longer include references to other env vars.  (We were not doing this anyway)

### Describe how to test/QA your changes
See #12820 repro steps, and validate that injected env vars now appear at the top of the env list and thus the dependent env vars render correctly.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

File: pkg/clusteragent/admission/mutate/common.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ func injectEnv(pod *corev1.Pod, env corev1.EnvVar) bool {
 			log.Debugf("Ignoring container '%s' in pod %s: env var '%s' already exist", ctr.Name, podStr, env.Name)
 			continue
 		}
-		pod.Spec.Containers[i].Env = append(pod.Spec.Containers[i].Env, env)
+		pod.Spec.Containers[i].Env = append([]corev1.EnvVar{env}, pod.Spec.Containers[i].Env...)
```
Comment (jcogilvie) [inline pkg/clusteragent/admission/mutate/common.go:69]: Note:  this has the effect of reversing the order of our injected env vars, since each is now prepended before the previous one.  This is why the tests have changed.

File: pkg/clusteragent/admission/mutate/config_test.go [hunk 2]
```diff
@@ -116,26 +116,32 @@ func TestInjectHostIP(t *testing.T) {
 	pod = withLabels(pod, map[string]string{"admission.datadoghq.com/enabled": "true"})
 	err := injectConfig(pod, "", nil)
 	assert.Nil(t, err)
-	assert.Equal(t, pod.Spec.Containers[0].Env[0].Name, "DD_AGENT_HOST")
-	assert.Equal(t, pod.Spec.Containers[0].Env[0].ValueFrom.FieldRef.FieldPath, "status.hostIP")
+	envs := pod.Spec.Containers[0].Env
+	lastEnv := envs[len(envs)-1]
```
Comment (jcogilvie) [inline pkg/clusteragent/admission/mutate/config_test.go:120]: Something to consider:  this test is strongly coupled to the order of injected env vars.  Perhaps it would be cleaner to lookup the element from `Env` which matches the expected `Name`, and assert on its value.  This would be (in my opinion) an incremental improvement in the stability of these tests.

File: releasenotes/notes/admissioncontroller-prepend-env-vars-8d88283457c55d9b.yaml [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+# must be readable independently of the other.
+#
+# Each section note must be formatted as reStructuredText.
+---
+enhancements:
+  - |
+    when injecting env vars with the admission controller, env
+    vars are now prepended instead of appended, meaning that 
+    kubernetes [dependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/)
+    can now depend on said injected vars.
```
Comment (buraizu) [inline releasenotes/notes/admissioncontroller-prepend-env-vars-8d88283457c55d9b.yaml:14]:
```suggestion
    When injecting env vars with the admission controller, env
    vars are now prepended instead of appended, meaning that 
    Kubernetes [dependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/)
    can now depend on these injected vars. 
```

**Review by buraizu — COMMENTED** [review]
Thanks, suggested some minor edits to the release note

File: pkg/clusteragent/admission/mutate/common.go (hunk 1 above)
Comment (ahmed-mez) [reply pkg/clusteragent/admission/mutate/common.go:69]: Could you add a comment to explain why we prepend? (can be added in the function doc string as well).

File: pkg/clusteragent/admission/mutate/config_test.go (hunk 2 above)
Comment (ahmed-mez) [reply pkg/clusteragent/admission/mutate/config_test.go:120]: Agreed, feel free to do so :)

File: releasenotes/notes/admissioncontroller-prepend-env-vars-8d88283457c55d9b.yaml [hunk 4]
```diff
@@ -0,0 +1,14 @@
+# Each section from every release note are combined when the
```
Comment (ahmed-mez) [inline releasenotes/notes/admissioncontroller-prepend-env-vars-8d88283457c55d9b.yaml:1]: Please move this file to the release notes directory  of the cluster agent (`releasenotes-dca/notes/`)

**Review by ahmed-mez — COMMENTED** [review]
Thanks for the contribution @jcogilvie ! Added a few minor comments.

File: pkg/clusteragent/admission/mutate/config_test.go (hunk 2 above)
Comment (jcogilvie) [reply pkg/clusteragent/admission/mutate/config_test.go]: Done.  Although now I'm left wondering whether we actually *do* care about order now, since our env vars are supposed to precede the other ones.

**Review by ahmed-mez — APPROVED** [review]

**Review by buraizu — APPROVED** [review]
