### PR TITLE
fix the `getEmbeddedBTF` platform selection algorithm

### LINKED ISSUE #21042: [BUG] slices.DeleteFunc
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/DataDog/datadog-agent/blob/main/pkg/ebpf/btf.go#L243):

```
			// remove possible paths that do not match possible platforms
			slices.DeleteFunc(possiblePaths, func(s string) bool {
				pform := strings.Split(s, string(os.PathSeparator))[0]
				return !slices.Contains(kvp.platforms, pform)
			})
```

which doesn't do what it seems to do, and should look like this instead:

```
			// remove possible paths that do not match possible platforms
			possiblePaths = slices.DeleteFunc(possiblePaths, func(s string) bool {
				pform := strings.Split(s, string(os.PathSeparator))[0]
				return !slices.Contains(kvp.platforms, pform)
			})
```

I have not tried to execute it.

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

As reported in https://github.com/DataDog/datadog-agent/issues/21042 the usage of `slices.DeleteFunc` is wrong. This PR adds a test exercising this code path (and failing) in the first commit. And fixes the issue in the second.

Fixes https://github.com/DataDog/datadog-agent/issues/21042

Here is the change for the testdata archive:

```
# added:
centos
|- centos/3.10.0-1062.0.0.0.1.el7.x86_64.btf.tar.xz
fakecentos
|- centos/3.10.0-1062.0.0.0.1.el7.x86_64.btf.tar.xz
```

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

File: pkg/ebpf/btf.go [hunk 1]
```diff
@@ -240,7 +240,7 @@ func (b *orderedBTFLoader) getEmbeddedBTF(platform, platformVersion, kernelVersi
 	for _, kvp := range kernelVersionPatterns {
 		if kvp.pattern.MatchString(kernelVersion) {
 			// remove possible paths that do not match possible platforms
-			slices.DeleteFunc(possiblePaths, func(s string) bool {
+			possiblePaths := slices.DeleteFunc(possiblePaths, func(s string) bool {
```
Comment (Deleplace) [inline pkg/ebpf/btf.go:243]: I suspect a nasty bug here using `:=` instead of `=`.

The new local var `possiblePaths` is shadowing the real `possiblePaths`, and doesn't fail compilation as unused because it's read at line 247.

But the original `possiblePaths` is then left in an inconsistent state.

**Review by Deleplace — CHANGES_REQUESTED** [review]

**Review by usamasaqib — APPROVED** [review]
