### PR TITLE
Don't stop the agent when journald is stopped or crashes

### LINKED ISSUE #1555: Agent doesn't restart on journald failure
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

==============
Agent (v6.0.3)
==============

  Status date: 2018-04-04 23:15:12.440773 UTC
  Pid: 920
  Python Version: 2.7.12
  Logs: 
  Check Runners: 1
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -0.000200632 s
    System UTC time: 2018-04-04 23:15:12.440773 UTC

  Host Info
  =========
    bootTime: 2018-02-17 00:06:22.000000 UTC
    kernelVersion: 4.13.0-1006-gcp
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 16.04
    procs: 249
    uptime: 3.872051e&#43;06

  Hostnames
  =========
    host_aliases: [internal-v6mx.findmine-153506]
    hostname: internal-v6mx.c.findmine-153506.internal
    socket-fqdn: internal-v6mx.c.findmine-153506.internal.
    socket-hostname: internal-v6mx

=========
Collector
=========

  Running Checks
  ==============
    cpu
    ---
      Total Runs: 12348
      Metrics: 6, Total Metrics: 74082
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    disk
    ----
      Total Runs: 12348
      Metrics: 66, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    file_handle
    -----------
      Total Runs: 12348
      Metrics: 1, Total Metrics: 12348
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    http_check
    ----------
      Total Runs: 12348
      Metrics: 3, Total Metrics: 37042
      Events: 0, Total Events: 0
      Service Checks: 1, Total Service Checks: 12348
  
    http_check
    ----------
      Total Runs: 12348
      Metrics: 3, Total Metrics: 37044
      Events: 0, Total Events: 0
      Service Checks: 1, Total Service Checks: 12348
  
    io
    --
      Total Runs: 12348
      Metrics: 26, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    load
    ----
      Total Runs: 12348
      Metrics: 6, Total Metrics: 74088
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    memory
    ------
      Total Runs: 12348
      Metrics: 14, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    network
    -------
      Total Runs: 12348
      Metrics: 20, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
    ntp
    ---
      Total Runs: 12348
      Metrics: 1, Total Metrics: 12085
      Events: 0, Total Events: 0
      Service Checks: 1, Total Service Checks: 12348
  
    process
    -------
      Total Runs: 12348
      Metrics: 16, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 1, Total Service Checks: 12348
  
    process
    -------
      Total Runs: 12348
      Metrics: 16, Total Metrics: over 100K
      Events: 0, Total Events: 0
      Service Checks: 1, Total Service Checks: 12348
  
    uptime
    ------
      Total Runs: 12348
      Metrics: 1, Total Metrics: 12348
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  CheckRunsV1: 12349
  IntakeV1: 941
  RetryQueueSize: 0
  Success: 25639
  TimeseriesV1: 12349

  API Keys status
  ===============
    https://6-0-3-app.agent.datadoghq.com,*************************7e41c: API Key valid

==========
Logs Agent
==========

  Logs Agent is not running

=========
DogStatsD
=========

  Checks Metric Sample: 2.438814e&#43;06
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 12349
  Series Flushed: 1.987483e&#43;06
  Service Check: 222264
  Service Checks Flushed: 234595
  Dogstatsd Metric Sample: 120461
```

**Describe what happened:**
The Datadog agent unit goes into an inactive state and does not restart automatically. I believe the root cause is a journald crash (when the system becomes overloaded it kills journald) which in turn kills log pipes for certain processes (included datadog-agent) and the agent doesn't recover.

**Describe what you expected:**
The agent restarts are journald crashes.

**Steps to reproduce the issue:**
1. Stop `systemd-journald` (`sudo systemctl stop systemd-journald`).
1. After about 10 seconds observe that `datadog-agent` goes to `inactive` and doesn't restart.

**Additional environment details (Operating System, Cloud provider, etc):**
Running on Ubuntu 16.04 in Google Compute Engine. systemd version 229-4ubuntu21.1. It sounds like it could be a systemd issue and related to https://bugs.freedesktop.org/show_bug.cgi?id=84923. But I'm not quite sure...

Perhaps the agent should be catching and handling `SIGPIPE`? More information about this at https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Stream%20logging.

The status of the unit before failure:

```
andy@internal-v6mx:~$ sudo systemctl status datadog-agent
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-04 23:23:33 UTC; 1min 0s ago
 Main PID: 5711 (agent)
    Tasks: 16
   Memory: 39.1M
      CPU: 885ms
   CGroup: /system.slice/datadog-agent.service
           └─5711 /opt/datadog-agent/bin/agent/agent start -p /opt/datadog-agent/run/agent.pid

Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check load
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check load
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check memory
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check memory
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check network
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check network
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check ntp
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check ntp
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check uptime
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check uptime
```

And after failure:

```
andy@internal-v6mx:~$ sudo systemctl status datadog-agent
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2018-04-04 23:24:34 UTC; 4s ago
  Process: 5711 ExecStart=/opt/datadog-agent/bin/agent/agent start -p /opt/datadog-agent/run/agent.pid (code=killed, signal=PIPE)
 Main PID: 5711 (code=killed, signal=PIPE)

Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check load
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check load
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check memory
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check memory
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check network
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check network
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check ntp
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check ntp
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:246 in work) | Running check uptime
Apr 04 23:24:19 internal-v6mx agent[5711]: 2018-04-04 23:24:19 UTC | INFO | (runner.go:302 in work) | Done running check uptime
```

### PR DESCRIPTION
**Pull request by remicalixte**
### What does this PR do?

By default systemd redirect the stdout to journald. When journald is stopped or crashes we receive a SIGPIPE signal. Go ignore SIGPIPE signals unless it is when stdout or stdout is closed, in this case the agent is stopped. We don't want that so we intercept the SIGPIPE signals and just discard them using the new `--ignore-sigpipe` flag

Other small fix, don't display the absolute path of the source files when using syslog:
before:
```
Oct 04 20:41:03 ubuntu-xenial agent[22041]: INFO | (/go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:258) | Running check memory
```
after:
```
Oct 04 20:42:06 ubuntu-xenial agent[22501]: INFO | (runner.go:258) | Running check memory
```

### Motivation

Fix https://github.com/DataDog/datadog-agent/issues/1555

### CODE REVIEW

**Comment by remicalixte** [comment]
This issue also affects the trace agent, but not the process agent. I don't know what to do for this one.

**Comment by nmuesch** [comment]
Hey! Thanks for this @remicalixte It seems I'm currently hitting this issue in one of my environments. In my case it seems like its the Trace Agent thats experiencing the issue. Would it be possible to extend this to Trace and Process as well?

**Comment by palazzem** [comment]
On APM side, we're waiting for your review before merging https://github.com/DataDog/datadog-trace-agent/pull/486

**Review by arbll — DISMISSED** [review]
LGTM. Just a question by curiosity: why don't just ignore `SIGPIPE` by default ?

**Comment by gbbr** [comment]
Good question. Do we need the flag?

**Comment by remicalixte** [comment]
I wanted to change the default behavior in the fewest case possible. With the flag we don't ignore `SIGPIPE` when we run the `datadog-agent status` command for example, and stopping when we receive a `SIGPIPE` is the behavior of many unix command line programs. There is a bit of info there: https://golang.org/pkg/os/signal/#pkg-overview.

File: cmd/agent/app/run.go [hunk 1]
```diff
@@ -81,6 +84,19 @@ func run(cmd *cobra.Command, args []string) error {
 		}
 	}()
 
+	// By default systemd redirect the stdout to journald. When journald is stopped or crashes we receive a SIGPIPE signal.
+	// Go ignore SIGPIPE signals unless it is when stdout or stdout is closed, in this case the agent is stopped. We don't want that
+	// so we intercept the SIGPIPE signals and just discard them.
+	if ignoreSigpipe {
```
Comment (olivielpeau) [inline cmd/agent/app/run.go]: any reason not to use [`signal.Ignore`](https://golang.org/pkg/os/signal/#Ignore) instead of this custom logic?

**Review by olivielpeau — COMMENTED** [review]
just a question, disregard if it's not relevant

**Comment by arbll** [comment]
The current implementation is scoped to `run` & `start` so it would not interfere with the other commands. I think the question is if there is a case where we want to exit a running agent when we get a `SIGPIPE` for `stdout` or `stderr`. I would answer no but I might be missing something.

Regardless both options are fine for me

File: cmd/agent/app/run.go (hunk 1 above)
Comment (remicalixte) [reply cmd/agent/app/run.go]: `signal.Ignore` only undoes the effect of `signal.Notify`. The doc is not very clear about it but I've tried this first

**Comment by remicalixte** [comment]
Oh yes you're right. I guess the flag is not really necessary then...

**Comment by remicalixte** [comment]
The process agent is already ignoring all signals for example. I think it's fine to always ignore `SIGPIPE`s

File: cmd/agent/app/run.go [hunk 2]
```diff
@@ -81,6 +81,17 @@ func run(cmd *cobra.Command, args []string) error {
 		}
 	}()
 
+	// By default systemd redirect the stdout to journald. When journald is stopped or crashes we receive a SIGPIPE signal.
```
Comment (olivielpeau) [inline cmd/agent/app/run.go]: nit: `redirects`

File: cmd/agent/app/run.go [hunk 3]
```diff
@@ -81,6 +81,17 @@ func run(cmd *cobra.Command, args []string) error {
...
+	// Go ignore SIGPIPE signals unless it is when stdout or stdout is closed, in this case the agent is stopped. We don't want that
```
Comment (olivielpeau) [inline cmd/agent/app/run.go]: nit: `ignores`. Also, it's not very clear what `we don't want that` refers to, maybe this would be clearer: `We never want the agent to stop upon receiving SIGPIPE, so [...]`

File: pkg/config/log.go [hunk 4]
```diff
@@ -110,7 +110,7 @@ func SetupLogger(logLevel, logFile, uri string, rfc, logToConsole, jsonFormat bo
 		<format id="json" format="{&quot;time&quot;:&quot;%%Date(%s)&quot;,&quot;level&quot;:&quot;%%LEVEL&quot;,&quot;file&quot;:&quot;%%File&quot;,&quot;line&quot;:&quot;%%Line&quot;,&quot;func&quot;:&quot;%%FuncShort&quot;,&quot;msg&quot;:&quot;%%Msg&quot;}%%n"/>
 		<format id="common" format="%%Date(%s) | %%LEVEL | (%%File:%%Line in %%FuncShort) | %%Msg%%n"/>
 		<format id="syslog-json" format="%%CustomSyslogHeader(20,`+strconv.FormatBool(rfc)+`){&quot;level&quot;:&quot;%%LEVEL&quot;,&quot;relfile&quot;:&quot;%%RelFile&quot;,&quot;line&quot;:&quot;%%Line&quot;,&quot;msg&quot;:&quot;%%Msg&quot;}%%n"/>
-		<format id="syslog-common" format="%%CustomSyslogHeader(20,`+strconv.FormatBool(rfc)+`) %%LEVEL | (%%RelFile:%%Line) | %%Msg%%n" />
+		<format id="syslog-common" format="%%CustomSyslogHeader(20,`+strconv.FormatBool(rfc)+`) %%LEVEL | (%%File:%%Line) | %%Msg%%n" />
```
Comment (olivielpeau) [inline pkg/config/log.go]: to give slightly more context, we use `(%%File:%%Line in %%FuncShort)` for agent.log (for ex: `somefile.go:23 in myFunction)`, I think we should normalize to the latter unless there's a good reason not to

**Review by olivielpeau — DISMISSED** [review]
Looks good, just a few nits :)

File: pkg/config/log.go (hunk 4 above)
Comment (remicalixte) [reply pkg/config/log.go]: Yes I agree

**Review by olivielpeau — APPROVED** [review]
👌👌

File: cmd/agent/app/run.go (hunk 1 above)
Comment (gbbr) [reply cmd/agent/app/run.go]: I was amazed by this assumption and had to try it out. My intention was not to test the validity of your statement, but to actually open an issue on [golang/go](https://github.com/golang/go) to correct the documentation. However, when trying it out, it seems that what you say is not true. Feel free to try it out yourself with this simple program:

```go
package main

import (
	"os/signal"
	"syscall"
	"time"
)

func main() {
	signal.Ignore(syscall.SIGINT)
	time.Sleep(5 * time.Second)
}
```
You can experiment with and without the `Ignore` call.

Comment (remicalixte) [reply cmd/agent/app/run.go]: SIGPIPE is a special case for go (it even has its own section in the documentation here: https://golang.org/pkg/os/signal/). The documentation also suggests to use `Notify` for what we want to do. I'm building a package of the agent using Ignore just to be sure. We can find it on gitlab on the branch remicalixte/sigpipe once the pipeline is finished. I will test in with journald since I don't know of any other setup where you can get a `SIGPIPE` from stdout without killing your process.

Comment (remicalixte) [reply cmd/agent/app/run.go]: I can confirm `Ignore` is not enough
```
vagrant@ubuntu-xenial:/etc/datadog-agent$ sudo systemctl status datadog-agent
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-10-12 14:44:18 UTC; 3s ago
 Main PID: 2051 (agent)
    Tasks: 10
   Memory: 20.5M
      CPU: 510ms
   CGroup: /system.slice/datadog-agent.service
           └─2051 /opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid

Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check memory with an interval of 15s
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check network
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check network with an interval of 15s
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check ntp
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check ntp with an interval of 15s
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:63 in Schedule) | Scheduling check uptime
Oct 12 14:44:19 ubuntu-xenial agent[2051]: 2018-10-12 14:44:19 UTC | INFO | (scheduler.go:76 in Enter) | Scheduling check uptime with an interval of 15s
Oct 12 14:44:20 ubuntu-xenial agent[2051]: 2018-10-12 14:44:20 UTC | INFO | (runner.go:258 in work) | Running check cpu
Oct 12 14:44:20 ubuntu-xenial agent[2051]: 2018-10-12 14:44:20 UTC | INFO | (runner.go:324 in work) | Done running check cpu
Oct 12 14:44:21 ubuntu-xenial agent[2051]: 2018-10-12 14:44:21 UTC | INFO | (serializer.go:242 in SendMetadata) | Sent host metadata payload, size: 3359 bytes.
vagrant@ubuntu-xenial:/etc/datadog-agent$ sudo systemctl stop systemd-journald
Warning: Stopping systemd-journald.service, but it can still be activated by:
  systemd-journald-dev-log.socket
  systemd-journald.socket
  systemd-journald-audit.socket
vagrant@ubuntu-xenial:/etc/datadog-agent$ sudo systemctl status datadog-agent
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2018-10-12 14:44:39 UTC; 2s ago
  Process: 2051 ExecStart=/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid (code=killed, signal=PIPE)
 Main PID: 2051 (code=killed, signal=PIPE)

Oct 12 14:44:31 ubuntu-xenial agent[2051]: 2018-10-12 14:44:31 UTC | INFO | (runner.go:324 in work) | Done running check uptime
Oct 12 14:44:32 ubuntu-xenial agent[2051]: 2018-10-12 14:44:32 UTC | INFO | (runner.go:258 in work) | Running check network
Oct 12 14:44:32 ubuntu-xenial agent[2051]: 2018-10-12 14:44:32 UTC | WARN | (datadog_agent.go:149 in LogMessage) | (base.py:223) | DEPRECATION NOTICE: `device_name` is deprecated, please use a `device:` tag in the `tags` list instead
Oct 12 14:44:32 ubuntu-xenial agent[2051]: 2018-10-12 14:44:32 UTC | INFO | (runner.go:324 in work) | Done running check network
Oct 12 14:44:33 ubuntu-xenial agent[2051]: 2018-10-12 14:44:33 UTC | INFO | (runner.go:258 in work) | Running check load
Oct 12 14:44:33 ubuntu-xenial agent[2051]: 2018-10-12 14:44:33 UTC | INFO | (runner.go:324 in work) | Done running check load
Oct 12 14:44:34 ubuntu-xenial agent[2051]: 2018-10-12 14:44:34 UTC | INFO | (runner.go:258 in work) | Running check file_handle
Oct 12 14:44:34 ubuntu-xenial agent[2051]: 2018-10-12 14:44:34 UTC | INFO | (runner.go:324 in work) | Done running check file_handle
Oct 12 14:44:35 ubuntu-xenial agent[2051]: 2018-10-12 14:44:35 UTC | INFO | (runner.go:258 in work) | Running check cpu
Oct 12 14:44:35 ubuntu-xenial agent[2051]: 2018-10-12 14:44:35 UTC | INFO | (runner.go:324 in work) | Done running check cpu
vagrant@ubuntu-xenial:/etc/datadog-agent$
```
- agent is running
- we kill journald
- agent exited with a SIGPIPE

Comment (gbbr) [reply cmd/agent/app/run.go]: Thanks for clarifying this.
