### PR TITLE
Fix default security-agent logs file

### LINKED ISSUE #6334: security-agent writes /var/log/datadog/agent.log as root
In 6.22 security-agent is now enabled by default. I see this immediately shuts down as it is not enabled in the config, but it runs as root and logs to /var/log/datadog/agent.log:

`# ls -l /var/log/datadog/agent.log
-rw-r--r-- 1 root root 1095 Sep  8 08:48 /var/log/datadog/agent.log`

This means that the main datadog agent cannot write to the agent.log and we see a seelog error in stdout:

```journalctl -f -u datadog-agent
-- Logs begin at Tue 2020-09-01 11:50:33 UTC. --
Sep 08 08:52:45 <host> agent[1896]: seelog internal error: invalid argument
```

I believe that if security-agent must run as root then it should log to a different log file.

### PR DESCRIPTION
**Pull request by clamoriniere**
### What does this PR do?

fixes: #6334

Define a dedicated logs file for the security-agent

### Motivation

fix reported issue  #6334 

### Additional Notes

N/A

### Describe your test plan

Activate the security-agent and check that security agent logs is written in the "security-agent.log" file

### CODE REVIEW

File: cmd/agent/common/common_android.go [hunk 1]
```diff
@@ -16,6 +16,8 @@ const (
 	DefaultLogFile = "/var/log/datadog/agent.log"
 	// DefaultDCALogFile points to the log file that will be used if not configured
 	DefaultDCALogFile = "/var/log/datadog/cluster-agent.log"
+	// DefaultSecuriyAgentLogFile points to the log file that will be used by the security-agent if not configured
+	DefaultSecuriyAgentLogFile = "/var/log/datadog/security-agent.log"
```
Comment (KSerrania) [inline cmd/agent/common/common_android.go:20]:
```suggestion
	DefaultSecurityAgentLogFile = "/var/log/datadog/security-agent.log"
```

File: cmd/agent/common/common_darwin.go [hunk 2]
```diff
@@ -16,6 +16,8 @@ const (
 	DefaultLogFile = "/var/log/datadog/agent.log"
 	// DefaultDCALogFile points to the log file that will be used if not configured
 	DefaultDCALogFile = "/var/log/datadog/cluster-agent.log"
+	// DefaultSecuriyAgentLogFile points to the log file that will be used by the security-agent if not configured
+	DefaultSecuriyAgentLogFile = "/var/log/datadog/security-agent.log"
```
Comment (KSerrania) [inline cmd/agent/common/common_darwin.go:20]:
```suggestion
	DefaultSecurityAgentLogFile = "/var/log/datadog/security-agent.log"
```

File: cmd/agent/common/common_nix.go [hunk 3]
```diff
@@ -22,6 +22,8 @@ const (
 	DefaultLogFile = "/var/log/datadog/agent.log"
 	// DefaultDCALogFile points to the log file that will be used if not configured
 	DefaultDCALogFile = "/var/log/datadog/cluster-agent.log"
+	// DefaultSecuriyAgentLogFile points to the log file that will be used by the security-agent if not configured
+	DefaultSecuriyAgentLogFile = "/var/log/datadog/security-agent.log"
```
Comment (KSerrania) [inline cmd/agent/common/common_nix.go:26]:
```suggestion
	// DefaultSecurityAgentLogFile points to the log file that will be used by the security-agent if not configured
	DefaultSecurityAgentLogFile = "/var/log/datadog/security-agent.log"
```

File: cmd/agent/common/common_windows.go [hunk 4]
```diff
@@ -46,6 +46,8 @@ var (
 	DefaultLogFile = "c:\\programdata\\datadog\\logs\\agent.log"
 	// DefaultDCALogFile points to the log file that will be used if not configured
 	DefaultDCALogFile = "c:\\programdata\\datadog\\logs\\cluster-agent.log"
+	// DefaultSecuriyAgentLogFile points to the log file that will be used by the security-agent if not configured
+	DefaultSecuriyAgentLogFile = "c:\\programdata\\datadog\\logs\\security-agent.log"
```
Comment (KSerrania) [inline cmd/agent/common/common_windows.go:50]:
```suggestion
	// DefaultSecurityAgentLogFile points to the log file that will be used by the security-agent if not configured
	DefaultSecurityAgentLogFile = "c:\\programdata\\datadog\\logs\\security-agent.log"
```

File: cmd/agent/common/common_windows.go [hunk 5]
```diff
@@ -54,6 +56,7 @@ func init() {
 		DefaultConfPath = pd
 		DefaultLogFile = filepath.Join(pd, "logs", "agent.log")
 		DefaultDCALogFile = filepath.Join(pd, "logs", "cluster-agent.log")
+		DefaultSecuriyAgentLogFile = filepath.Join(pd, "logs", "security-agent.log")
```
Comment (KSerrania) [inline cmd/agent/common/common_windows.go:59]:
```suggestion
		DefaultSecurityAgentLogFile = filepath.Join(pd, "logs", "security-agent.log")
```

File: cmd/security-agent/api/agent/agent.go [hunk 6]
```diff
@@ -125,7 +125,7 @@ func (a *Agent) makeFlare(w http.ResponseWriter, r *http.Request) {
 	w.Header().Set("Content-Type", "application/json")
 	logFile := config.Datadog.GetString("log_file")
 	if logFile == "" {
-		logFile = common.DefaultLogFile
+		logFile = common.DefaultSecuriyAgentLogFile
```
Comment (KSerrania) [inline cmd/security-agent/api/agent/agent.go:128]:
```suggestion
		logFile = common.DefaultSecurityAgentLogFile
```

File: cmd/security-agent/app/app.go [hunk 7]
```diff
@@ -133,7 +133,7 @@ func start(cmd *cobra.Command, args []string) error {
 	syslogURI := coreconfig.GetSyslogURI()
 	logFile := coreconfig.Datadog.GetString("log_file")
 	if logFile == "" {
-		logFile = common.DefaultLogFile
+		logFile = common.DefaultSecuriyAgentLogFile
```
Comment (KSerrania) [inline cmd/security-agent/app/app.go:136]:
```suggestion
		logFile = common.DefaultSecurityAgentLogFile
```

File: cmd/security-agent/app/flare.go [hunk 8]
```diff
@@ -81,6 +81,9 @@ func requestFlare(caseID string) error {
 	urlstr := fmt.Sprintf("https://localhost:%v/agent/flare", config.Datadog.GetInt("security_agent.cmd_port"))
 
 	logFile := config.Datadog.GetString("log_file")
+	if logFile == "" {
+		logFile = common.DefaultSecuriyAgentLogFile
```
Comment (KSerrania) [inline cmd/security-agent/app/flare.go:85]:
```suggestion
		logFile = common.DefaultSecurityAgentLogFile
```

**Review by ahmed-mez — APPROVED** [review]

File: cmd/security-agent/api/agent/agent.go [hunk 9]
```diff
@@ -125,7 +125,7 @@ func (a *Agent) makeFlare(w http.ResponseWriter, r *http.Request) {
 	w.Header().Set("Content-Type", "application/json")
 	logFile := config.Datadog.GetString("log_file")
```
Comment (KSerrania) [inline cmd/security-agent/api/agent/agent.go:126]: We should have a different config setting (maybe `security_agent.log_file`), otherwise the Agent and Security Agent will log to the same file if `log_file` is set.

File: cmd/security-agent/app/flare.go (hunk 8 above)
Comment (L3n41c) [inline cmd/security-agent/app/flare.go:85]: If no log file is specified in config, the `security-agent` will now use a different default log file from the core agent.
But if a log file is specified in the config, then the `security-agent` and the core agent will both use it.
Shouldn’t we have another config item for the `security-agent` log file ?

File: cmd/security-agent/api/agent/agent.go (hunk 9 above)
Comment (clamoriniere) [reply cmd/security-agent/api/agent/agent.go]: done

File: cmd/security-agent/app/flare.go (hunk 8 above)
Comment (clamoriniere) [reply cmd/security-agent/app/flare.go]: done

File: pkg/config/config.go [hunk 10]
```diff
@@ -762,6 +762,7 @@ func InitConfig(config Config) {
 	// Datadog security agent (common)
 	config.BindEnvAndSetDefault("security_agent.cmd_port", 5010)
 	config.BindEnvAndSetDefault("security_agent.expvar_port", 5011)
+	config.BindEnvAndSetDefault("security_agent.log_file", "")
```
Comment (L3n41c) [inline pkg/config/config.go:765]: This way of defining `security_agent.log_file` is consistent with the way the `log_file` parameter is defined.

But I’m wondering why we couldn’t set the default value here.
```suggestion
	config.BindEnvAndSetDefault("security_agent.log_file", common.DefaultSecurityAgentLogFile)
```

so that we don’t need to handle the default value case each time we want to use that parameter:
```diff
  logFile := coreconfig.Datadog.GetString("security_agent.log_file")
- if logFile == "" {
-   logFile = common.DefaultSecurityAgentLogFile
- }
```
in `cmd/security-agent/api/agent/agent.go`, `cmd/security-agent/app/app.go` and `cmd/security-agent/app/flare.go`

Comment (clamoriniere) [reply pkg/config/config.go]: indeed make sens

**Review by L3n41c — APPROVED** [review]

File: pkg/config/config.go [hunk 11]
```diff
@@ -20,6 +20,7 @@ import (
 
 	yaml "gopkg.in/yaml.v2"
 
+	"github.com/DataDog/datadog-agent/cmd/agent/common"
```
Comment (KSerrania) [inline pkg/config/config.go:23]: Seems like this import creates a cycle:
```
package github.com/DataDog/datadog-agent/cmd/agent
	imports github.com/DataDog/datadog-agent/cmd/agent/app
	imports github.com/DataDog/datadog-agent/cmd/agent/api
	imports github.com/DataDog/datadog-agent/cmd/agent/api/agent
	imports github.com/DataDog/datadog-agent/cmd/agent/api/response
	imports github.com/DataDog/datadog-agent/pkg/autodiscovery/integration
	imports github.com/DataDog/datadog-agent/pkg/util/containers
	imports github.com/DataDog/datadog-agent/pkg/config
	imports github.com/DataDog/datadog-agent/cmd/agent/common
	imports github.com/DataDog/datadog-agent/pkg/autodiscovery
	imports github.com/DataDog/datadog-agent/pkg/autodiscovery/configresolver
	imports github.com/DataDog/datadog-agent/pkg/autodiscovery/listeners
	imports github.com/DataDog/datadog-agent/pkg/config
```

Not sure how to fix this though 😞.

Comment (clamoriniere) [reply pkg/config/config.go:23]: yes I will, define the defaultSecurityAgentLogsFile in another package, since it is only used in config now

Comment (clamoriniere) [reply pkg/config/config.go]: @KSerrania, I finally remove the circular dependency issue.

File: pkg/config/config_windows.go [hunk 12]
```diff
@@ -28,6 +30,7 @@ func osinit() {
 		defaultConfdPath = filepath.Join(pd, "conf.d")
 		defaultAdditionalChecksPath = filepath.Join(pd, "checks.d")
 		defaultRunPath = filepath.Join(pd, "run")
+		defaultSecurityAgentLogFile = filepath.Join(pd, "security-agent.log")
```
Comment (lebauce) [inline pkg/config/config_windows.go:33]: Shouldn't it be "logs", "security-agent.log" (like in `pkg/process/config/config_windows.go`) ?

Comment (clamoriniere) [reply pkg/config/config_windows.go]: yes, your are right! thanks

**Review by lebauce — APPROVED** [review]

**Review by olivielpeau — APPROVED** [review]
LGTM
