### PR TITLE
fix(jmxfetch): check if DSD UDS listener is available before selecting a transport

### LINKED ISSUE #43745: [BUG] JMXFetch getDSDStatus is flawed
### Agent version

7.72.1

### Bug Report

https://github.com/DataDog/datadog-agent/pull/32919 by @tobz introduced a new way of detecting whether DogStatsD Server is running via UDP or UDS, but it's flawed:

https://github.com/DataDog/datadog-agent/blob/main/pkg/jmxfetch/jmxfetch.go#L531-L536
```
udsEnabled := pkgconfigsetup.Datadog().GetString("dogstatsd_socket") != ""
udpEnabled := pkgconfigsetup.Datadog().GetInt("dogstatsd_port") != 0

if dsdEnabled && udsEnabled {
	return DSDStatusRunningUDSDatagram
}
```

This code only checks if the `dogstatsd_socket` config is set in the agent config but it does not check if UDS is actually running. If Datadog agent is running on an environment where the Unix account does not have permission to write to the path specified in `dogstatsd_socket` (e.g. a daemonset in Kubernetes), JMXFetch will still assume UDS is running and send metrics to the non-existent socket and fail.

```
2025-12-02T16:47:15Z | JMX | ERROR | StatsD-Sender-pool-3-thread-1 | LoggingErrorHandler | statsd client error:
java.io.IOException: No such file or directory
        at jnr.unixsocket.UnixDatagramChannel.send(UnixDatagramChannel.java:176)
        at com.timgroup.statsd.StatsDSender$2.run(StatsDSender.java:103)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Reproduction Steps

_No response_

### Agent configuration

Default Configuration

### Operating System

Debian 6.12.47 x86_64 GNU/Linux

### Other environment details

_No response_

### PR DESCRIPTION
**Pull request by tobz**
### What does this PR do?

Updates the logic used by the JMXFetch runner to determine the best DogStatsD transport to assert that, when attempting to use UDS, that the UDS socket is actually present.

### Motivation

In #32919, we changed the behavior of the aforementioned logic to support DSD being run by either the Core Agent _or_ Agent Data Plane. This involved removing a check that actively introspected the DSD component to see if the UDS listener was active. The thinking was that it was both irrelevant for ADP and that the logic of the DSD component in the Core Agent would always spawn the UDS listener if `dogstatsd_socket` was non-empty, so checking if it was listening was extraneous.

However, the original logic was added at a time when `dogstatsd_socket` had no default value, and in 7.57, we updated the default value. However, in some cases, the underlying directory that the default socket path uses would not get created automatically, leading the UDS listener to fail to properly create the socket and listen. With the old logic checking if the UDS listener was running, the JMXFetch could gracefully handle this scenario... but with our change to _remove_ that logic, it no longer handled it gracefully, and tried to forcefully use UDS regardless of whether or not there was an actual UDS listener present. No bueno.

This PR adds back a direct check -- is the UDS listener present? -- but adapted to handle both Core Agent _or_ ADP being the ones running the listener: we check for the presence of the socket, and that it's a socket file. If neither of those things are true, we simply default to UDP. This brings back the previous behavior but in a way that is acceptable for both use cases.

### Describe how you validated your changes

New unit tests were added for the helper functions we added to check for the presence of the UDS listener, as well as for the new `getPreferredDSDEndpoint` function which picks the optimal DSD transport to use subject to whether or not the hypothetical best transport is actually available.

### CODE REVIEW

**Review by jeremy-hanna — APPROVED** [review]
👍 for agent-runtime owned files

File: pkg/util/net/endpoint_check_test.go [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+	"os"
+	"path/filepath"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestIsUDSAvailable_NonExistentPath(t *testing.T) {
+	assert.False(t, IsUDSAvailable("/tmp/does-not-exist-dsd-test.sock"))
```
Comment (StephenWakely) [inline pkg/util/net/endpoint_check_test.go]: This is very slightly fragile. You could use `os.MkdirTemp` as in the other tests. Same for line 31.

**Review by StephenWakely — APPROVED** [review]
A very minor nit on the test, but otherwise looks good.

File: pkg/util/net/endpoint_check_test.go (hunk 1 above)
Comment (tobz) [reply pkg/util/net/endpoint_check_test.go]: Good catch. I'll make that change. 👍🏻

Comment (tobz) [reply pkg/util/net/endpoint_check_test.go]: Fixed in c2167e9eb8.
