### PR TITLE
[CONTP-1253] Avoid using subdirectories in monutpaths for UDS sockets when possible

### LINKED ISSUE #45952: [BUG] Breaking change in 7.72.0 for UDS paths
### Agent version

7.72.0

### Bug Report

Opening this issue mostly to provide feedback and request improvement to documentation for default Unix Domain Socket paths. The following change should also be listed as breaking in the 7.72.0 release for users that rely on the "default" `unixDomainSocketConfig.path` value.

[CONTP-841]: [Fixed a bug for handling hostpath on Admission Controller #40766](https://github.com/DataDog/datadog-agent/pull/40766)

```golang
if (i.config.dogStatsDAgentHostSocket != i.config.traceAgentHostSocket) || isSocketVol || useCSI {
    apmMountBase = apmMountBase + "/" + apmSubdir
    dsdMountBase = dsdMountBase + "/" + dsdSubdir
}
```
https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/admission/mutate/config/mutator.go#L142-L145

We're using the Datadog Operator for Kubernetes and cluster agents inject host socket volumes to pods.

The subdirectories added to socket paths by this change broke trace clients in our clusters because we expected the path to be `/var/run/datadog/apm.socket`. We didn't expect it to change out from under us.

`/var/run/datadog/apm.socket` -> `/var/run/datadog/apm/apm.socket`

The change took us by surprise because everywhere in documentation (and code) `/var/run/datadog/apm.socket` appears to be the default path.

There is nowhere [except this page](https://docs.datadoghq.com/containers/kubernetes/apm/?tab=datadogoperator#configure-the-datadog-agent-to-collect-traces) where `/var/run/datadog/apm/apm.socket` is ever mentioned, and that page even contradicts itself calling out `/var/run/datadog/apm.socket` as the default in the Datadog Operator example.

It's unclear from documentation what the true default should be, and release notes for 7.72.0 did not mention anything about paths changing.

~We resolved this by setting `unixDomainSocketConfig.path` explicitly to the old path.~

**EDIT:**
We've found that setting `unixDomainSocketConfig.path` actually has no effect on the paths. We have not been able to find a way to override them to the old non-nested paths.

This is a major problem because we set `DD_TRACE_AGENT_URL` in our chart. We would really like a way to be able to use the prior socket paths.

[CONTP-841]: https://datadoghq.atlassian.net/browse/CONTP-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adel121**
### What does this PR do?

Resolves [Issue #45952 ](https://github.com/DataDog/datadog-agent/issues/45952)

This PR updates the cluster agent admission controller to make sure that sub directories for apm and dsd sockets are not added in case the volume type is socket.

Previously, this was introduced in 7.72.0 to make implementation and testing simpler. The change done in 7.72.0 is backwards compatible, and the change done in this PR is backward compatible as well. 

### Motivation

Although the change introduced in 7.72.0 was not a breaking change, the customer was explicitly overriding the `TRACE_AGENT_URL` environment variable injected by the admission controller. When the admission controller changed the mountpath, the environment variable was adapted by the admission controller as well to make sure things still work. But since the env var was explicitly overwritten by the customer, it broke the setup. 

The user's case can be fixed by removing the explicit overwrite for `TRACE_AGENT_URL` env var. However, this requires patching their internal helm charts and waiting all internal apps to rollout. 

The change done in this PR helps overcome this by only having to rollout the agent.

More information can be found in [Issue #45952 ](https://github.com/DataDog/datadog-agent/issues/45952)

### Describe how you validated your changes

Unit tests & E2E tests.

### CODE REVIEW

**Review by zhuminyi — APPROVED** [review]

**Review by Mathew-Estafanous — APPROVED** [review]
Change looks good. Thanks!

File: pkg/clusteragent/admission/mutate/config/mutator.go [hunk 1]
```diff
@@ -139,7 +139,13 @@ func (i *Mutator) MutatePod(pod *corev1.Pod, _ string, _ dynamic.Interface) (boo
 		apmMountBase := i.config.socketPath
 		dsdMountBase := i.config.socketPath
 
-		if (i.config.dogStatsDAgentHostSocket != i.config.traceAgentHostSocket) || isSocketVol || useCSI {
+		// If we are using a CSI driver, we always mount 2 volumes to avoid confusion.
+		// CSI volume types are: APMSocketDirectory, DSDSocketDirectory, APMSocket, DSDSocket.
+		// Although mounting only DSDSocketDirectory is sufficient in case sockets are in the same directory, we prefer mounting APMSocketDirectory and DSDSocketDirectory as well to avoid confusion.
+		//
+		// If the user requests socket volumes, we will not have a conflict because each file is mounted separately on a different mount point.
+		// In this case, we have no need for the subdirectories.
```
Comment (Mathew-Estafanous) [inline pkg/clusteragent/admission/mutate/config/mutator.go:147]: Not necessary at all, but we could maybe reference the github issue or PR for additional context.
