### PR TITLE
[docker] check nil pointers on docker client return values

### LINKED ISSUE #1681: unknown panic
I'm not quite sure how to reproduce this, but I've observed this panic in the agent.

```
[ AGENT ] panic: runtime error: invalid memory address or nil pointer dereference
[ AGENT ] [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x910564]
[ AGENT ]
[ AGENT ] goroutine 120 [running]:
[ AGENT ] github.com/DataDog/datadog-agent/pkg/util/docker.(*DockerUtil).dockerContainers(0xc4204520c0, 0xc42019da8e, 0x0, 0x0, 0x0, 0x0, 0x0)
[ AGENT ]       /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/docker/docker_util.go:164 +0xb34
[ AGENT ] github.com/DataDog/datadog-agent/pkg/util/docker.(*DockerUtil).Containers(0xc4204520c0, 0xc42019da8e, 0x0, 0x0, 0x0, 0x2, 0x2)
[ AGENT ]       /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/docker/docker_util.go:234 +0x11ed
[ AGENT ] github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers.(*DockerCheck).Run(0xc4201505b0, 0x7ab2b3af1, 0x30b34e0)
[ AGENT ]       /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker.go:160 +0x246
[ AGENT ] github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).work(0xc4219434a0)
[ AGENT ]       /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:255 +0x4a1
[ AGENT ] created by github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).AddWorker
[ AGENT ]       /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:100 +0x8a
[ AGENT ] AGENT EXITED WITH CODE 2, SIGNAL 0, KILLING CONTAINER
[PROCESS] trace-agent exited with code 256, signal 15, restarting in 2 seconds
```

Agent version:
```
Agent 6.2.0-rc.1 - Commit: aecc560 - Serialization version: 4.7
```

### PR DESCRIPTION
**Pull request by xvello**
### What does this PR do?

Remove the naked inspect call in `DockerUtil.dockerContainers`, to use `DockerUtil.Inspect` that checks for a `nil` `ContainerJSONBase` embed before using it. See [the type definition](https://godoc.org/github.com/docker/engine-api/types#ContainerJSON).

I also tracked down a possible nil pointer dereference while accessing `NetworkSettings` without check it's not nil, fixing this one too.

### Motivation

Fixes #1681

### CODE REVIEW

**Review by mfpierre — DISMISSED** [review]
LGTM

File: pkg/util/docker/docker_util.go [hunk 1]
```diff
@@ -155,17 +158,12 @@ func (d *DockerUtil) dockerContainers(cfg *ContainerListConfig) ([]*Container, e
...
-				// FIXME: Use du.Inspect instead
-				i, err := d.cli.ContainerInspect(ctx, c.ID)
-				if err != nil && client.IsErrContainerNotFound(err) {
+				i, err := d.Inspect(c.ID, false)
+				if err != nil {
 					d.Unlock()
 					log.Debugf("Error inspecting container %s: %s", c.ID, err)
 					continue
 				}
-				if i.ContainerJSONBase == nil {
```
Comment (xvello) [inline pkg/util/docker/docker_util.go]: `d.Inspect` already checks for this. Added in https://github.com/DataDog/datadog-agent/pull/1684 as a quick fix for 6.2.0

**Review by mfpierre — APPROVED** [review]
