### PR TITLE
[ntp] renames `ntp.offset{source:intake}` to `ntp.intake_offset`

### LINKED ISSUE #48789: [BUG] new source:intake tag for ntp.offset is a breaking change
### Agent version

7.77.2

### Bug Report

The new feature `[NTP] generate ntp.offset metric based on intake's HTTP response` , PR: https://github.com/DataDog/datadog-agent/pull/45664 from @ian28223  is actually a breaking change, while it's nice to have a way to detect drift behind firewalls:
- It created a lot of false positives on our monitors.
- Sharing the same metric name `ntp.offset` is misleading; a name like `ntp.http_fallback_offset` would have been clearer.
- Also, it doesn't account for network latency, unlike NTP, showing much higher values.

We had some unusual NTP drift reported above, near -900 ms since March 19, when we started having hosts with this new feature, probably because my team is using the us5 Datadog endpoint while running systems in AWS us-west-2.

Since reverting this would also be a breaking change, maybe a documentation update would be the bare minimum? (https://docs.datadoghq.com/integrations/ntp/?tab=host) + nothing mention this in the config file

This new feature has been published as an enhancement under [7.77.0](https://github.com/DataDog/datadog-agent/releases/tag/7.77.0)

Anyway, thanks for the new feature and have a nice day :)

### Reproduction Steps

_No response_

### Agent configuration

default ntp configuration

### Operating System

6.8.0-1050-aws #53-Ubuntu SMP Fri Mar  6 11:05:48 UTC 2026 aarch64 aarch64 aarch64 GNU/Linux

### Other environment details

AWS, us-west-2, EC2 hosts

### PR DESCRIPTION
**Pull request by ian28223**
### What does this PR do?

- Renames the intake-derived clock offset metric from ntp.offset (tagged source:intake) to a distinct metric ntp.intake_offset (no source tag).
- All unit test expectations updated to match the new metric name
agent status Clocks display is unchanged — it reads from the corechecks_net_ntp_intake_time_offset expvar directly

### Motivation

- PR #45664 introduced ntp.offset{source:intake} alongside the existing ntp.offset{source:ntp}. Existing monitors querying ntp.offset without a tag filter began aggregating over two time series instead of one, shifting the average and triggering false alerts.
- Using a separate metric name (ntp.intake_offset) fully decouples intake-based clock monitoring from NTP-based monitoring, leaving existing ntp.offset monitors unaffected.

### Describe how you validated your changes

- Verified all modified packages compile successfully
- Confirmed agent status Clocks section continues to display both NTP offset and Intake offset (expvar-based, unaffected by metric rename)

### Additional Notes

- Fixes #48789

### CODE REVIEW

**Review by fabbing — APPROVED** [review]

File: pkg/collector/corechecks/net/ntp/ntp.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ func (c *NTPCheck) Run() error {
 		serviceCheckStatus = servicecheck.ServiceCheckOK
 	}
 
-	_ = sender.GaugeWithTimestamp("ntp.offset", clockOffset, "", []string{"source:ntp"}, ts)
```
Comment (thom-vend) [inline pkg/collector/corechecks/net/ntp/ntp.go:251]: This is a new breaking changed, someone might have added a filter to source:ntp and will get their monitor broken and without any data at the next update.
We already have a version published with this tag  `source:ntp` ; Maybe leave the tag?

Comment (ian28223) [reply pkg/collector/corechecks/net/ntp/ntp.go:251]: It will take about a month for this change to take effect when upgraded to. Feel free to adjust the monitorquery from `ntp.offset{source:ntp}` to `ntp.offset{!source:intake}`
