### PR TITLE
[process-agent] [system-probe] Remove initial logger from startup

### LINKED ISSUE #4300: Process agent doesn't honour DD_LOG_LEVEL or DD_LOG_FILE
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v6.14.0)
===============

  Status date: 2019-10-15 10:09:08.138050 UTC
  Agent start: 2019-10-15 10:07:33.946896 UTC
  Pid: 57
  Go Version: go1.12.9
  Python Version: 2.7.16
  Check Runners: 4

  Log File: /app/.apt/var/log/datadog/datadog.log
  Log Level: OFF

  Paths
  =====
    Config File: /app/.apt/etc/datadog-agent/datadog.yaml
    conf.d: /app/.apt/etc/datadog-agent/conf.d
    checks.d: /app/.apt/etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 436µs
    System UTC time: 2019-10-15 10:09:08.138050 UTC

  Host Info
  =========
    bootTime: 2019-10-04 00:44:06.000000 UTC
    kernelVersion: 4.4.0-1048-aws
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 18.04
    procs: 66
    uptime: 273h23m30s
    virtualizationRole: guest
    virtualizationSystem: lxc

  Hostnames
  =========

< removed>

=========
Collector
=========



  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 6, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    disk (2.5.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 236, Total: 1,416
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 54ms


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 5, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 221, Total: 1,173
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 6, Total: 36
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 17, Total: 102
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    network (1.11.4)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 31, Total: 186
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 2ms


    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1, Total: 6
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 18ms


    postgres (3.1.3)
    ----------------
      Instance ID: postgres:73f440dbfafc8f68 [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/postgres.d/conf.yaml
      Total Runs: 7
      Metric Samples: Last Run: 14, Total: 98
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 7
      Average Execution Time : 28ms


    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1, Total: 6
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 6
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 2
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 14
    TimeseriesV1: 6

  API Keys status
  ===============
    API key ending with 2a1cd: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 2a1cd

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 3,194
  Dogstatsd Metric Sample: 435
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 6
  Series Flushed: 1,993
  Service Check: 69
  Service Checks Flushed: 71

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 434
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 27,682
  Udp Packet Reading Errors: 0
  Udp Packets: 435
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
```

**Describe what happened:**

Running the agent in Heroku. I have `DD_LOG_LEVEL` set to `OFF` and correctly, the trace agent and the main agent stop logging, but the process agent is still logging:

```
2019-10-15 10:18:18 UTC | PROCESS | INFO | (pkg/process/config/config.go:378 in loadEnvVariables) | overriding API key from env DD_API_KEY value
```

Also, I have `DD_LOG_FILE` set to `/app/.apt/var/log/datadog/datadog.log` but the process agent is still trying to write to the default path, which is read-only in Heroku:

```
seelog internal error: mkdir /var/log/datadog/: read-only file system
```

**Describe what you expected:**

The process agent honours the `DD_LOG_LEVEL` and `DD_LOG_FILE` settings

**Additional environment details (Operating System, Cloud provider, etc):**

Heroku Buildpack

### PR DESCRIPTION
**Pull request by robertjli**
### What does this PR do?

This PR removes the initial logger from startup. The initial logger is not necessary because the log package buffers logs that are written before the logger is initialized, so no logs will be lost. In the case of error logs, these are automatically written to stdout as well, so they can be captured if the application quits before the log is flushed. This initial logger does not respect any logging config variables, which was the underlying issue behind https://github.com/DataDog/datadog-agent/issues/4300.

This PR also changes the map of environment variable and config variable names to a slice. Because we explicitly intend for certain variables to override others (e.g. `DD_LOG_LEVEL` is preferred over `LOG_LEVEL`), we must iterate through these variables in order, and a map does not guarantee iteration order.

### Motivation

[PROC-24](https://datadoghq.atlassian.net/browse/PROC-24)
Fixes https://github.com/DataDog/datadog-agent/issues/4300

### Additional Notes

@DataDog/processes 
@DataDog/networks

### CODE REVIEW

File: pkg/process/config/config.go [hunk 1]
```diff
@@ -379,36 +379,36 @@ func NewSystemProbeConfig(loggerName config.LoggerName, yamlPath string) (*Agent
 }
 
 func loadEnvVariables() {
-	for envKey, cfgKey := range map[string]string{
-		"DD_PROCESS_AGENT_CONTAINER_SOURCE": "process_config.container_source",
-		"DD_SCRUB_ARGS":                     "process_config.scrub_args",
-		"DD_STRIP_PROCESS_ARGS":             "process_config.strip_proc_arguments",
-		"DD_PROCESS_AGENT_URL":              "process_config.process_dd_url",
-		"DD_ORCHESTRATOR_URL":               "process_config.orchestrator_dd_url",
+	for _, variable := range []struct{ env, cfg string }{
```
Comment (kevinconaway) [inline pkg/process/config/config.go]: Would you please add a comment here about the order being important?  I see the note below about preferring DD_LOG_LEVEL over LOG_LEVEL but it would be good to have a note up top for visibility.

**Review by kevinconaway — DISMISSED** [review]

File: pkg/process/config/config.go (hunk 1 above)
Comment (robertjli) [reply pkg/process/config/config.go]: Done!

**Review by kevinconaway — APPROVED** [review]
