### PR TITLE
[serverless] Remove alias from function ARN

### LINKED ISSUE #8980: Serverless: Lambda alias invocations do not pick up AWS tags
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

A stack was created with a single hello world lambda.  The lambda was tested twice from the AWS UI.  Once, the function was tested directly, and the other time the alias was tested.  The tags that were defined on the function were not picked up in the alias trace. Also, the service header on the span reverted back to `aws.lambda` rather than the defined `service` tag.

**Describe what you expected:**

I expected the spans and the tags to match

**Steps to reproduce the issue:**

### Define the stack

**./bin/test_datadog_enhanced.ts**
```ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestDatadogEnhancedStack } from '../lib/test_datadog_enhanced-stack';

const app = new cdk.App();
new TestDatadogEnhancedStack(app, 'TestDatadogEnhancedStack', {
  /* If you don't specify 'env', this stack will be environment-agnostic.
   * Account/Region-dependent features and context lookups will not work,
   * but a single synthesized template can be deployed anywhere. */

  /* Uncomment the next line to specialize this stack for the AWS Account
   * and Region that are implied by the current CLI configuration. */
  // env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },

  /* Uncomment the next line if you know exactly what Account and Region you
   * want to deploy the stack to. */
  // env: { account: '123456789012', region: 'us-east-1' },

  /* For more information, see https://docs.aws.amazon.com/cdk/latest/guide/environments.html */
});
```

**./lib/handler/helloWorld.ts**
```ts
export const handler = async (event: any, context: any) => {
  return "Hello world";
};
```

**./lib/test_datadog-enhanced-stack.ts**
```ts
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs";
import { Construct, Stack, StackProps, Tags } from "@aws-cdk/core";
import { Datadog } from "datadog-cdk-constructs";

export class TestDatadogEnhancedStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    Tags.of(this).add("env", "datadog-test");
    Tags.of(this).add("service", "datadog-test");

    const fn = new NodejsFunction(this, "Function", {
      entry: "./lib/handler/helloWorld.ts",
      functionName: "datadog-test",
      memorySize: 512,
    });

    fn.currentVersion.addAlias("live");

    const dd = new Datadog(this, "Datadog", {
      nodeLayerVersion: 61,
      extensionLayerVersion: 10,
      apiKey: "api-key",
    });

    dd.addLambdaFunctions([fn]);
  }
}
```

### Deploy the stack

```bash
yarn cdk deploy
```

### Test the function

image (1)

### Test the alias

image (2)

### Compare the spans

image (3)

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by hghotra**
### What does this PR do?

- Remove the alias from the function ARN. This is available through `AWS_LAMBDA_FUNCTION_VERSION`.  

### Motivation
- Fixes #8980 
- Fixes issue with logs having different `hostname` when called with an alias, resulting in invocation page not showing invocations made using an alias. Traces don't show up as a result of the invocations not showing up, since we use request ids returned by the initial logs query.

**Without Alias**

image

**With Alias (before fix):**

image

**With Alias (after fix):**

image

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by DarcyRaynerDD — APPROVED** [review]
LGTM

File: pkg/serverless/serverless_test.go [hunk 1]
```diff
@@ -65,3 +65,16 @@ func TestComputeTimeout(t *testing.T) {
...
+	invokedFunctionArn := "arn:aws:lambda:eu-south-1:601427279990:function:inferred-spans-function-urls-dev-harv-function-urls:$latest"
+	functionArn := functionArnWithoutAlias(invokedFunctionArn)
+	expectedArn := "arn:aws:lambda:eu-south-1:601427279990:function:inferred-spans-function-urls-dev-harv-function-urls"
+	assert.Equal(t, functionArn, expectedArn)
+}
+
+func TestFunctionArnWithoutAliasWithoutAlias(t *testing.T) {
+	invokedFunctionArn := "arn:aws:lambda:eu-south-1:601427279990:function:inferred-spans-function-urls-dev-harv-function-urls"
+	functionArn := functionArnWithoutAlias(invokedFunctionArn)
+	assert.Equal(t, functionArn, functionArn)
```
Comment (nhinsch) [inline pkg/serverless/serverless_test.go:79]: I think this will always pass, did you mean `assert.Equal(t, functionArn, invokedFunctionArn)`?

File: pkg/serverless/serverless.go [hunk 2]
```diff
@@ -238,3 +239,14 @@ func computeTimeout(now time.Time, deadlineMs int64, safetyBuffer time.Duration)
 	currentTimeInMs := now.UnixNano() / int64(time.Millisecond)
 	return time.Duration((deadlineMs-currentTimeInMs)*int64(time.Millisecond) - int64(safetyBuffer))
 }
+
+func functionArnWithoutAlias(functionArn string) string {
```
Comment (nhinsch) [inline pkg/serverless/serverless.go:243]: The last part of the function Arn is actually called a qualifier. It can be an alias but it can also be a specific version number.

Also, I would name functions as verbs, and the things they return as nouns.

So, I would rename this function `removeQualifierFromArn()`
