### PR TITLE
Fixed a race condition for docker logs for short lived containers

### LINKED ISSUE #3955: No logs from short-lived (non-Kubernetes) containers
I've been having difficulty retrieving logs from short-lived containers. I recognize there's been some effort recently to improve this situation for Kubernetes based systems in #3372 - however, for those not on Kubernetes (like my team) our containers are still not showing logs. #3930 will help slightly, but for truly short-lived containers it's still possible for them to be missed.

Is it possible to look into scheduling at least one log collection for dead containers? From the discussion in #3930 it sounds like it should be feasible, but will need some investigation. I thought I'd open a ticket to ensure discussion happens in a more appropriate thread 😄 

**Steps to reproduce the issue:**
I have the datadog agent to forward logs for all containers that have a service defined, and use the following command on an ECS instance to mimic a short-lived container:
```bash
docker run \
  --label "com.datadoghq.ad.logs=[{\"source\": \"testing\", \"service\": \"testing\"}]" \
  --label "com.amazonaws.ecs.cluster=staging" \
  --label "com.amazonaws.ecs.container-name=testing" \
  alpine \
  ping -c1 google.com
```
Changing the command to `ping -c10 google.com` causes the logs to be picked up and collected, but a truly short-lived container does not have its logs collected 😢.

The current workaround is to have a script as the entrypoint/command for our containers that executes a `sleep` at the end so that regardless of exit status, the logs have a chance to be picked up. This is obviously far from ideal, though.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS ECS

### PR DESCRIPTION
**Pull request by ajacquemot**
### What does this PR do?

* Fixed a race condition where docker logs would not be collected for short lived containers because the socket was returning `EOF` because no logs were outputted yet.

* Fixed another race condition which was making the tailer restart on a reader close error when the tailer was supposed to stop.

### Motivation

Make sure logs for short lived containers are properly collected.

### Additional Notes

Let's add end-to-end tests to make sure we don't have regression on this, we can't write a unit-test yet because we did not mock the docket client, e.g. https://github.com/DataDog/datadog-agent/pull/3981

This should fix https://github.com/DataDog/datadog-agent/issues/3955

### CODE REVIEW

File: pkg/logs/input/docker/tailer.go [hunk 1]
```diff
@@ -184,8 +191,11 @@ func (t *Tailer) readForever() {
 					return
 				case err == io.EOF:
 					// This error is raised when the container is stopping
-					t.source.RemoveInput(t.ContainerID)
```
Comment (mfpierre) [inline pkg/logs/input/docker/tailer.go]: we don't need that call anymore?

Comment (ajacquemot) [reply pkg/logs/input/docker/tailer.go]: good catch

**Review by mfpierre — DISMISSED** [review]

File: pkg/logs/input/docker/tailer.go [hunk 2]
```diff
@@ -170,6 +170,13 @@ func (t *Tailer) readForever() {
 			n, err := t.read(inBuf, readTimeout)
 			if err != nil { // an error occurred, stop from reading new logs
 				switch {
+				case isReaderClosed(err):
+					// The reader has been closed during the shut down process of the tailer
+					// because as stated in the code base of docker:
+					// "It's up to the caller to close the stream.".
```
Comment (blemale) [inline pkg/logs/input/docker/tailer.go]: It is not easy to grasp that when the reader stops, it return a `http: read on closed response body` error, which signals to the tailer that it should stop.
