### PR TITLE
AP-2013 Modify ntp check to return error when no ntp are reachable

### LINKED ISSUE #15255: [BUG] Agent logs failure to connect to Datadog's NTP servers, but reports the checks to be OK
Agent logs failure to connect to Datadog's NTP servers, but reports the checks to be OK

**Agent Environment**
Agent version 7.38.1

**Describe what happened:**
No NTP metrics being reported by DD agent, on Windows 2016 servers since OS patches. It was noted after a few months that the metrics are. The auto monitor "Clock in sync with NTP", shows all green for all servers even those which are not reporting NTP status. The status checks on DD Agent admin portal shows OK for NTP.
The logs in the agent admin portal 
```
<timestamp> | CORE | INFO | (pkg/collector/corechecks/net/ntp.go:174 in Run) | Failed to get clock offset from any ntp host
<timestamp> | CORE | WARN | (pkg/collector/corechecks/net/ntp.go:206 in queryOffset) | Couldn't query the ntp host 3.datadog.pool.ntp.org for 10 times in a row: read udp hostIP:port->datadogIP:port: i/o timeout

```
**Describe what you expected:**
NTP status checks should have not showed OK if the NTP servers were not reachable
The auto monitor "Clock in sync with NTP" should have indicated that there is something wrong with the NTP metric. 

**Additional environment details (Operating System, Cloud provider, etc):**
Windows Server 2016 Datacenter. AWS EC2. 
2022-11 .NET Core 3.1.31 Update for x64 Server (KB5020930)
2022-11 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 x64 (KB5020614)
2022-11 Cumulative Update for Windows Server 2016 x64-based Systems (KB5019964)

### PR DESCRIPTION
**Pull request by KevinFairise2**
### What does this PR do?

Change NTP checks to return an error when no ntp servers are reachable.

Changed test to match new check behaviour, if no ntp servers are reachable, the checks is considered not working, and sends `UNKNOWN` status to Datadog App.
Fixes #15255

When no ntp servers are reachable:
30:05-NTPcheckchange
### Motivation

Currently status command would return OK for ntp check status even if no ntp server could be reached, that's confusing since the check is not working correctly.

### Describe how to test/QA your changes

- Deploy the agent
- Add a reachable ntp server to the conf.d/ntp.d/conf.yaml file
- Check that the NTP check status is OK and that service check is OK in Datadog App
- Change the configuration to an unreachable ntp (eg `unknown.ntp.org`)
- Check that the ntp check status is ERROR and that service check is UNKNOWN in Datadog App

### Reviewer's Checklist
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by chouetz — DISMISSED** [review]
LGTM

File: pkg/collector/corechecks/net/ntp.go [hunk 1]
```diff
@@ -171,21 +171,19 @@ func (c *NTPCheck) Run() error {
 
 	clockOffset, err := c.queryOffset()
 	if err != nil {
-		log.Info(err)
-		serviceCheckStatus = metrics.ServiceCheckUnknown
+		log.Error(err)
+		return err
```
Comment (KSerrania) [inline pkg/collector/corechecks/net/ntp.go:175]: Should the `ntp.in_sync` service check not be sent at all when there is an error?

File: releasenotes/notes/display-error-when-no-reachable-ntp-servers-3445de4a0fc0e1ab.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+
+fixes:
+  - |
+    Fixes Agent status displaying OK when all NTP servers are unreachable, if no NTP servers are reachable `datadog-agent status` will display NTP check in an `ERROR` state
```
Comment (kayayarai) [inline releasenotes/notes/display-error-when-no-reachable-ntp-servers-3445de4a0fc0e1ab.yaml:4]:
```suggestion
    If no NTP servers are reachable, `datadog-agent status` now displays `ERROR` for the NTP check, rather than `OK`.
```

**Review by kayayarai — APPROVED** [review]
Suggested rewording, 👍

File: pkg/collector/corechecks/net/ntp.go (hunk 1 above)
Comment (KevinFairise2) [reply pkg/collector/corechecks/net/ntp.go]: Service Check is now sent with `UNKNOWN` status when there is an error

File: pkg/collector/corechecks/net/ntp.go [hunk 3]
```diff
@@ -171,21 +171,19 @@ func (c *NTPCheck) Run() error {
 
 	clockOffset, err := c.queryOffset()
 	if err != nil {
-		log.Info(err)
-		serviceCheckStatus = metrics.ServiceCheckUnknown
```
Comment (amenasria) [inline pkg/collector/corechecks/net/ntp.go:175]: This seems to be missing IMO

**Review by amenasria — CHANGES_REQUESTED** [review]

**Review by amenasria — APPROVED** [review]
LGTM
