### PR TITLE
[pkg/config] Exclude DD_INSIDE_CI from being flagged as unknown env var

### LINKED ISSUE #10969: Unknown environment variable: DD_INSIDE_CI
**Describe what happened:**

I'm following [these instructions](https://docs.datadoghq.com/continuous_integration/setup_tests/agent/) to set up CI Test instrumentation, and it says to set up the following environment variable:

```
DD_INSIDE_CI (Required)
Disables the monitoring of the Datadog Agent container, as the underlying host is not accessible.
Default: false
Required value: true
```

But this doesn't seem to do anything:

```
2022-02-16 19:02:13 UTC | TRACE | WARN | (pkg/util/log/log.go:640 in func1) | Unknown environment variable: DD_INSIDE_CI
```

**Describe what you expected:**
I expected to not receive this log message because the documentation says it's a required variable. So either the documentation is wrong about which environment variable to set or it's wrong that setting this environment variable is "required" and leaving it unset is acceptable.

**Steps to reproduce the issue:**
Use the following docker compose:

```
version: '3.7'
services:
  dd-agent-ci:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY
      - DD_INSIDE_CI=true
      - DD_HOSTNAME=none
    ports:
      - 8126/tcp
```

And run it with:

```
DD_API_KEY=<your api key> docker-compose up dd-agent-ci
```

**Additional environment details (Operating System, Cloud provider, etc):**
N/A

### PR DESCRIPTION
**Pull request by sgnn7**
### What does this PR do?

Removes `DD_INSIDE_CI` from unknown env var warnings emitted by the agent.

### Motivation

This env var is externally tracked in the container startup scripts so
it can be safely ignored in the config checking for unknown variables.

### Additional Notes

Fixes: #10969 

### Possible Drawbacks / Trade-offs

N/A

### Describe how to test/QA your changes

- Run the agent with `DD_INSIDE_CI` variable set
- Ensure there are no warnings about this variable being unknown

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -1140,6 +1140,7 @@ func findUnknownEnvVars(config Config, environ []string) []string {
 	knownVars := map[string]struct{}{
 		// these variables are used by the agent, but not via the Config struct,
 		// so must be listed separately.
+		"DD_INSIDE_CI":      {},
```
Comment (hush-hush) [inline pkg/config/config.go:1143]: We need to add this to pkg/flare/envvars.go I think.

Comment (sgnn7) [reply pkg/config/config.go:1143]: Good catch. Fixed.

**Review by hush-hush — APPROVED** [review]
