### PR TITLE
pkg/trace/api: update info endpoint test to check only keys.

### LINKED ISSUE #13569: pkg/trace: `TestInfoHandler` is too restrictive
`TestInfoHandler` is too restrictive. It's checking that the entire output of /info doesn't change, when it really wants to just be checking that the keys don't change. That means that if we add a new endpoint, we end up with errors like this
```
go test ./... -run=TestInfoHandler
--- FAIL: TestInfoHandler (0.00s)
    --- FAIL: TestInfoHandler/default (0.00s)
        info_test.go:243: 
                Error Trace:    /Users/katie.hockman/go/src/github.com/DataDog/datadog-agent/pkg/trace/api/info_test.go:243
                Error:          Not equal: 
                                expected: "{\n\t\"version\": \"0.99.0\",\n\t\"git_commit\": \"fab047e10\",\n\t\"endpoints\": [\n\t\t\"/v0.3/traces\",\n\t\t\"/v0.3/services\",\n\t\t\"/v0.4/traces\",\n\t\t\"/v0.4/services\",\n\t\t\"/v0.5/traces\",\n\t\t\"/v0.7/traces\",\n\t\t\"/profiling/v1/input\",\n\t\t\"/telemetry/proxy/\",\n\t\t\"/v0.6/stats\",\n\t\t\"/v0.1/pipeline_stats\",\n\t\t\"/appsec/proxy/\",\n\t\t\"/evp_proxy/v1/\",\n\t\t\"/debugger/v1/input\"\n\t\t\"/dogstatsd/v1/proxy\"\n\t],\n\t\"feature_flags\": [\n\t\t\"feature_flag\"\n\t],\n\t\"client_drop_p0s\": true,\n\t\"span_meta_structs\": true,\n\t\"long_running_spans\": true,\n\t\"config\": {\n\t\t\"default_env\": \"prod\",\n\t\t\"target_tps\": 11,\n\t\t\"max_eps\": 12,\n\t\t\"receiver_port\": 8111,\n\t\t\"receiver_socket\": \"/sock/path\",\n\t\t\"connection_limit\": 12,\n\t\t\"receiver_timeout\": 100,\n\t\t\"max_request_bytes\": 123,\n\t\t\"statsd_port\": 123,\n\t\t\"max_memory\": 1000000,\n\t\t\"max_cpu\": 12345,\n\t\t\"analyzed_spans_by_service\": {\n\t\t\t\"X\": {\n\t\t\t\t\"Y\": 2.4\n\t\t\t}\n\t\t},\n\t\t\"obfuscation\": {\n\t\t\t\"elastic_search\": true,\n\t\t\t\"mongo\": true,\n\t\t\t\"sql_exec_plan\": true,\n\t\t\t\"sql_exec_plan_normalize\": true,\n\t\t\t\"http\": {\n\t\t\t\t\"remove_query_string\": true,\n\t\t\t\t\"remove_path_digits\": true\n\t\t\t},\n\t\t\t\"remove_stack_traces\": false,\n\t\t\t\"redis\": true,\n\t\t\t\"memcached\": false\n\t\t}\n\t}\n}"
                                actual  : "{\n\t\"version\": \"0.99.0\",\n\t\"git_commit\": \"fab047e10\",\n\t\"endpoints\": [\n\t\t\"/v0.3/traces\",\n\t\t\"/v0.3/services\",\n\t\t\"/v0.4/traces\",\n\t\t\"/v0.4/services\",\n\t\t\"/v0.5/traces\",\n\t\t\"/v0.7/traces\",\n\t\t\"/profiling/v1/input\",\n\t\t\"/telemetry/proxy/\",\n\t\t\"/v0.6/stats\",\n\t\t\"/v0.1/pipeline_stats\",\n\t\t\"/appsec/proxy/\",\n\t\t\"/evp_proxy/v1/\",\n\t\t\"/debugger/v1/input\",\n\t\t\"/dogstatsd/v1/proxy\"\n\t],\n\t\"feature_flags\": [\n\t\t\"feature_flag\"\n\t],\n\t\"client_drop_p0s\": true,\n\t\"span_meta_structs\": true,\n\t\"long_running_spans\": true,\n\t\"config\": {\n\t\t\"default_env\": \"prod\",\n\t\t\"target_tps\": 11,\n\t\t\"max_eps\": 12,\n\t\t\"receiver_port\": 8111,\n\t\t\"receiver_socket\": \"/sock/path\",\n\t\t\"connection_limit\": 12,\n\t\t\"receiver_timeout\": 100,\n\t\t\"max_request_bytes\": 123,\n\t\t\"statsd_port\": 123,\n\t\t\"max_memory\": 1000000,\n\t\t\"max_cpu\": 12345,\n\t\t\"analyzed_spans_by_service\": {\n\t\t\t\"X\": {\n\t\t\t\t\"Y\": 2.4\n\t\t\t}\n\t\t},\n\t\t\"obfuscation\": {\n\t\t\t\"elastic_search\": true,\n\t\t\t\"mongo\": true,\n\t\t\t\"sql_exec_plan\": true,\n\t\t\t\"sql_exec_plan_normalize\": true,\n\t\t\t\"http\": {\n\t\t\t\t\"remove_query_string\": true,\n\t\t\t\t\"remove_path_digits\": true\n\t\t\t},\n\t\t\t\"remove_stack_traces\": false,\n\t\t\t\"redis\": true,\n\t\t\t\"memcached\": false\n\t\t}\n\t}\n}"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -16,3 +16,3 @@
                                                "/evp_proxy/v1/",
                                -               "/debugger/v1/input"
                                +               "/debugger/v1/input",
                                                "/dogstatsd/v1/proxy"
                Test:           TestInfoHandler/default
        info_test.go:245: Output of /info has changed. Changing the keys is not allowed because the client rely on them and is considered a breaking change:
            
            {
                "version": "0.99.0",
                "git_commit": "fab047e10",
                "endpoints": [
                        "/v0.3/traces",
                        "/v0.3/services",
                        "/v0.4/traces",
                        "/v0.4/services",
                        "/v0.5/traces",
                        "/v0.7/traces",
                        "/profiling/v1/input",
                        "/telemetry/proxy/",
                        "/v0.6/stats",
                        "/v0.1/pipeline_stats",
                        "/appsec/proxy/",
                        "/evp_proxy/v1/",
                        "/debugger/v1/input",
                        "/dogstatsd/v1/proxy"
                ],
                "feature_flags": [
                        "feature_flag"
                ],
                "client_drop_p0s": true,
                "span_meta_structs": true,
                "long_running_spans": true,
                "config": {
                        "default_env": "prod",
                        "target_tps": 11,
                        "max_eps": 12,
                        "receiver_port": 8111,
                        "receiver_socket": "/sock/path",
                        "connection_limit": 12,
                        "receiver_timeout": 100,
                        "max_request_bytes": 123,
                        "statsd_port": 123,
                        "max_memory": 1000000,
                        "max_cpu": 12345,
                        "analyzed_spans_by_service": {
                                "X": {
                                        "Y": 2.4
                                }
                        },
                        "obfuscation": {
                                "elastic_search": true,
                                "mongo": true,
                                "sql_exec_plan": true,
                                "sql_exec_plan_normalize": true,
                                "http": {
                                        "remove_query_string": true,
                                        "remove_path_digits": true
                                },
                                "remove_stack_traces": false,
                                "redis": true,
                                "memcached": false
                        }
                }
            }
    --- FAIL: TestInfoHandler/debug (0.00s)
        info_test.go:243: 
                Error Trace:    /Users/katie.hockman/go/src/github.com/DataDog/datadog-agent/pkg/trace/api/info_test.go:243
                Error:          Not equal: 
                                expected: "{\n\t\"version\": \"0.99.0\",\n\t\"git_commit\": \"fab047e10\",\n\t\"endpoints\": [\n\t\t\"/v0.3/traces\",\n\t\t\"/v0.3/services\",\n\t\t\"/v0.4/traces\",\n\t\t\"/v0.4/services\",\n\t\t\"/v0.5/traces\",\n\t\t\"/v0.7/traces\",\n\t\t\"/profiling/v1/input\",\n\t\t\"/telemetry/proxy/\",\n\t\t\"/v0.6/stats\",\n\t\t\"/v0.1/pipeline_stats\",\n\t\t\"/appsec/proxy/\",\n\t\t\"/evp_proxy/v1/\",\n\t\t\"/debugger/v1/input\"\n\t],\n\t\"feature_flags\": [\n\t\t\"feature_flag\"\n\t],\n\t\"client_drop_p0s\": true,\n\t\"span_meta_structs\": true,\n\t\"long_running_spans\": true,\n\t\"config\": {\n\t\t\"default_env\": \"prod\",\n\t\t\"target_tps\": 11,\n\t\t\"max_eps\": 12,\n\t\t\"receiver_port\": 8111,\n\t\t\"receiver_socket\": \"/sock/path\",\n\t\t\"connection_limit\": 12,\n\t\t\"receiver_timeout\": 100,\n\t\t\"max_request_bytes\": 123,\n\t\t\"statsd_port\": 123,\n\t\t\"max_memory\": 1000000,\n\t\t\"max_cpu\": 12345,\n\t\t\"analyzed_spans_by_service\": {\n\t\t\t\"X\": {\n\t\t\t\t\"Y\": 2.4\n\t\t\t}\n\t\t},\n\t\t\"obfuscation\": {\n\t\t\t\"elastic_search\": true,\n\t\t\t\"mongo\": true,\n\t\t\t\"sql_exec_plan\": true,\n\t\t\t\"sql_exec_plan_normalize\": true,\n\t\t\t\"http\": {\n\t\t\t\t\"remove_query_string\": true,\n\t\t\t\t\"remove_path_digits\": true\n\t\t\t},\n\t\t\t\"remove_stack_traces\": false,\n\t\t\t\"redis\": true,\n\t\t\t\"memcached\": false\n\t\t}\n\t}\n}"
                                actual  : "{\n\t\"version\": \"0.99.0\",\n\t\"git_commit\": \"fab047e10\",\n\t\"endpoints\": [\n\t\t\"/v0.3/traces\",\n\t\t\"/v0.3/services\",\n\t\t\"/v0.4/traces\",\n\t\t\"/v0.4/services\",\n\t\t\"/v0.5/traces\",\n\t\t\"/v0.7/traces\",\n\t\t\"/profiling/v1/input\",\n\t\t\"/telemetry/proxy/\",\n\t\t\"/v0.6/stats\",\n\t\t\"/v0.1/pipeline_stats\",\n\t\t\"/appsec/proxy/\",\n\t\t\"/evp_proxy/v1/\",\n\t\t\"/debugger/v1/input\",\n\t\t\"/dogstatsd/v1/proxy\"\n\t],\n\t\"feature_flags\": [\n\t\t\"feature_flag\"\n\t],\n\t\"client_drop_p0s\": true,\n\t\"span_meta_structs\": true,\n\t\"long_running_spans\": true,\n\t\"config\": {\n\t\t\"default_env\": \"prod\",\n\t\t\"target_tps\": 11,\n\t\t\"max_eps\": 12,\n\t\t\"receiver_port\": 8111,\n\t\t\"receiver_socket\": \"/sock/path\",\n\t\t\"connection_limit\": 12,\n\t\t\"receiver_timeout\": 100,\n\t\t\"max_request_bytes\": 123,\n\t\t\"statsd_port\": 123,\n\t\t\"max_memory\": 1000000,\n\t\t\"max_cpu\": 12345,\n\t\t\"analyzed_spans_by_service\": {\n\t\t\t\"X\": {\n\t\t\t\t\"Y\": 2.4\n\t\t\t}\n\t\t},\n\t\t\"obfuscation\": {\n\t\t\t\"elastic_search\": true,\n\t\t\t\"mongo\": true,\n\t\t\t\"sql_exec_plan\": true,\n\t\t\t\"sql_exec_plan_normalize\": true,\n\t\t\t\"http\": {\n\t\t\t\t\"remove_query_string\": true,\n\t\t\t\t\"remove_path_digits\": true\n\t\t\t},\n\t\t\t\"remove_stack_traces\": false,\n\t\t\t\"redis\": true,\n\t\t\t\"memcached\": false\n\t\t}\n\t}\n}"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -16,3 +16,4 @@
                                                "/evp_proxy/v1/",
                                -               "/debugger/v1/input"
                                +               "/debugger/v1/input",
                                +               "/dogstatsd/v1/proxy"
                                        ],
                Test:           TestInfoHandler/debug
        info_test.go:245: Output of /info has changed. Changing the keys is not allowed because the client rely on them and is considered a breaking change:
            
            {
                "version": "0.99.0",
                "git_commit": "fab047e10",
                "endpoints": [
                        "/v0.3/traces",
                        "/v0.3/services",
                        "/v0.4/traces",
                        "/v0.4/services",
                        "/v0.5/traces",
                        "/v0.7/traces",
                        "/profiling/v1/input",
                        "/telemetry/proxy/",
                        "/v0.6/stats",
                        "/v0.1/pipeline_stats",
                        "/appsec/proxy/",
                        "/evp_proxy/v1/",
                        "/debugger/v1/input",
                        "/dogstatsd/v1/proxy"
                ],
                "feature_flags": [
                        "feature_flag"
                ],
                "client_drop_p0s": true,
                "span_meta_structs": true,
                "long_running_spans": true,
                "config": {
                        "default_env": "prod",
                        "target_tps": 11,
                        "max_eps": 12,
                        "receiver_port": 8111,
                        "receiver_socket": "/sock/path",
                        "connection_limit": 12,
                        "receiver_timeout": 100,
                        "max_request_bytes": 123,
                        "statsd_port": 123,
                        "max_memory": 1000000,
                        "max_cpu": 12345,
                        "analyzed_spans_by_service": {
                                "X": {
                                        "Y": 2.4
                                }
                        },
                        "obfuscation": {
                                "elastic_search": true,
                                "mongo": true,
                                "sql_exec_plan": true,
                                "sql_exec_plan_normalize": true,
                                "http": {
                                        "remove_query_string": true,
                                        "remove_path_digits": true
                                },
                                "remove_stack_traces": false,
                                "redis": true,
                                "memcached": false
                        }
                }
            }
FAIL
FAIL    github.com/DataDog/datadog-agent/pkg/trace/api  0.343s
ok      github.com/DataDog/datadog-agent/pkg/trace/api/apiutil  (cached) [no tests to run]
FAIL
```

### PR DESCRIPTION
**Pull request by knusbaum**
The tests for the info endpoint over-specify the output, making them fail and need to be updated whenever anything changes, rather than when a new key is added or removed.

This change ensures that the exact keys are present in the output, rather than checking specific values.

Fixes #13569

### CODE REVIEW

File: pkg/trace/api/info_test.go [hunk 1]
```diff
@@ -109,145 +293,56 @@ func TestInfoHandler(t *testing.T) {
...
-		},
+
+	rcv := newTestReceiverFromConfig(conf)
+	defer testutil.WithFeatures("feature_flag")()
+	_, h := rcv.makeInfoHandler()
+	rec := httptest.NewRecorder()
+	req := httptest.NewRequest("GET", "/info", nil)
+	h.ServeHTTP(rec, req)
+	var m map[string]interface{}
+	b, err := ioutil.ReadAll(rec.Body)
```
Comment (ajgajg1134) [inline pkg/trace/api/info_test.go:340]: Super nit:

You can save a few lines by doing `json.NewDecoder(rec.Body).Decode(&m)`

**Review by ajgajg1134 — DISMISSED** [review]

File: pkg/trace/api/info_test.go (hunk 1 above)
Comment (knusbaum) [reply pkg/trace/api/info_test.go]: Nice, you're right.

**Review by ajgajg1134 — APPROVED** [review]
