### PR TITLE
[ AGNTLOG-303 ] Fix logs agent incompatibility with systemd >= 256

### LINKED ISSUE #40416: [BUG] Datadog-agent crashes with SIGSEGV
Datadog agent crashes with SIGSEGV with a recent version of systemd. A different instance with systemd v252 and the same agent version works fine.

**Agent Environment**

Agent 7.69.4 - Commit: 9bd1f3ecfc - Serialization version: v5.0.158 - Go version: go1.24.6

configuration:

```
collect_ec2_tags: true
config_providers:
-   name: docker
    polling: true
listeners:
-   name: docker
log_level: WARN
logs_config:
    container_collect_all: true
logs_enabled: true
process_config:
    enabled: 'true'
    scrub_args: true

use_dogstatsd: true
dogstatsd_origin_detection: true
dogstatsd_socket: /var/run/datadog/dsd.socket
dogstatsd_port: 8125
bind_host: 127.0.0.1
```

**Describe what happened:**

Agent crashes with SIGSEGV and a very long stack trace and enters a restart loop.
```
agent[784790]: SIGSEGV: segmentation violation
agent[784790]: PC=0x2aa5d38 m=4 sigcode=1 addr=0x6ac1
agent[784790]: signal arrived during cgo execution
agent[784790]: goroutine 663 gp=0x40014f6540 m=4 mp=0x40000a5808 [syscall]:
agent[784790]: runtime.cgocall(0x2bb7f8c, 0x4001492cb8)
agent[784790]:         runtime/cgocall.go:167 +0x44 fp=0x4001492c80 sp=0x4001492c40 pc=0x4a9384
agent[784790]: github.com/coreos/go-systemd/sdjournal._Cfunc_my_sd_journal_enumerate_data(0xffff41662f48, 0xffff50003ce0, 0x4001284710, 0x40017ba2a8)
agent[784790]:         _cgo_gotypes.go:200 +0x34 fp=0x4001492cb0 sp=0x4001492c80 pc=0x1efdee4
agent[784790]: github.com/coreos/go-systemd/sdjournal.(*Journal).GetEntry.func6(...)
agent[784790]:         github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e/sdjournal/journal.go:770
agent[784790]: github.com/coreos/go-systemd/sdjournal.(*Journal).GetEntry(0x4001c23cb0)
agent[784790]:         github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e/sdjournal/journal.go:770 +0x6e4 fp=0x4001492e70 sp=0x4001492cb0 pc=0x1effea4
agent[784790]: github.com/DataDog/datadog-agent/pkg/logs/tailers/journald.(*Tailer).tail(0x40013aeb40)
agent[784790]:         github.com/DataDog/datadog-agent/pkg/logs/tailers/journald/tailer.go:282 +0x10c fp=0x4001492fb0 sp=0x4001492e70 pc=0x1f0274c
agent[784790]: github.com/DataDog/datadog-agent/pkg/logs/tailers/journald.(*Tailer).Start.gowrap2()
agent[784790]:         github.com/DataDog/datadog-agent/pkg/logs/tailers/journald/tailer.go:101 +0x28 fp=0x4001492fd0 sp=0x4001492fb0 pc=0x1f01908
agent[784790]: runtime.goexit({})
agent[784790]:         runtime/asm_arm64.s:1223 +0x4 fp=0x4001492fd0 sp=0x4001492fd0 pc=0x4b5904
agent[784790]: created by github.com/DataDog/datadog-agent/pkg/logs/tailers/journald.(*Tailer).Start in goroutine 442
agent[784790]:         github.com/DataDog/datadog-agent/pkg/logs/tailers/journald/tailer.go:101 +0x304
```

**Describe what you expected:**
No crash.

**Steps to reproduce the issue:**
Enable Log collection. If log collection is disabled, the agent does not crash.

**Additional environment details (Operating System, Cloud provider, etc):**

Running on an EC2 Instance with Fedora Linux 41 (Cloud Edition) as a sytemd unit.

systemd 256 (256.17-1.fc41)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE

### PR DESCRIPTION
**Pull request by ddrthall**
### What does this PR do?
A libzstd version mismatch within the agent code is causing issues with newer versions of systemd, namely the [datadog/zstd](https://github.com/DataDog/zstd) go dependency is set [within the agent](https://github.com/DataDog/datadog-agent/blob/1db7ec98d4f91cca55b21f1f616094ac9efeb723/go.mod#L54) to v1.5.6 but the embedded libzstd.so.1 we're packaging with the agent is set to v1.5.5. This can cause a segfault on all versions of systemd >= 256, because [version 256](https://github.com/systemd/systemd/releases/tag/v256-rc1) introduced a change to how the systemd library dynamically links to local libzstd libraries.

In order to resolve this issue, this MR seeks to align the two versions of libzstd together onto version 1.5.6

### Describe how you validated your changes
Agent versions deployed with this change onto journald-enabled systems that reliably experience the segfault resolve the segfault. 

Additionally, the expectation is that all libraries currently attempting to load version 1.5.5 via dynamic linking are actually getting the statically compiled 1.5.6 in its entirety. Any library attempting to dynamically load 1.5.5 is expected to break in the same manner that systemd does. Correspondingly, updating the 1.5.5 version to 1.5.6 is locked to be either a fix or a no-op, rather than a potential avenue for expected version mismatch.

### Additional Notes
resolves #40416

### CODE REVIEW

**Review by soberpeach — APPROVED** [review]

File: omnibus/config/software/zstd.rb [hunk 1]
```diff
@@ -15,15 +15,15 @@
 #
 
 name "zstd"
-default_version "1.5.5"
```
Comment (jszwedko) [inline omnibus/config/software/zstd.rb:18]: Would it make sense to add comments here and elsewhere where we specify zstd version to help reduce the risk that they stay in-sync?

Are there ways we could have automated tests for this?

Comment (jszwedko) [reply omnibus/config/software/zstd.rb:18]: (Can follow up on both of these)

**Review by brett0000FF — APPROVED** [review]

**Review by JSGette — APPROVED** [review]
