### PR TITLE
admission controller: Set failure policy

### LINKED ISSUE #11426: Admission controller option to fail on error
I want to be able to set the [`failurePolicy`](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) of the datadog admission controller.

The controller currently [uses the `Ignore` failurePolicy](https://github.com/DataDog/datadog-agent/blob/d05e41f7d2e7cd92c3df2a618410a31bfe19a880/pkg/clusteragent/admission/controllers/webhook/controller_v1.go#L201).  This is safe, but should be configurable in the cluster agent (and helm chart).  

Use case:  presently, some of my services validate that `DD_AGENT_HOST` is set upon startup.  If those services start before the admission controller is ready, the variable is never injected but kubernetes keeps trying to restart the failed containers, rather than rescheduling the pods.  If instead I make the controller fail on error, they will be rescheduled and hence readmitted and can come alive in their own time.  

It's possible that this should be contingent on setting [high availability mode](https://github.com/DataDog/helm-charts/blob/0316b0ec18de7eda72279c3b683770efa502ffc7/charts/datadog/templates/NOTES.txt#L263) for the cluster agent.

### PR DESCRIPTION
**Pull request by nrgraham23**
### What does this PR do?
This PR adds the ability to configure the failure policy for the admission controller.

### Motivation
Fixes: #11426

> Use case: presently, some of my services validate that DD_AGENT_HOST is set upon startup. If those services start before the admission controller is ready, the variable is never injected but kubernetes keeps trying to restart the failed containers, rather than rescheduling the pods. If instead I make the controller fail on error, they will be rescheduled and hence readmitted and can come alive in their own time.

### Additional Notes
We also considered using a boolean instead of a string since there are only two options, but decided to go with a string as it seemed more self explanatory.

### Possible Drawbacks / Trade-offs
The default value for this config option will remain the same.  There should be no real drawbacks.

### Describe how to test/QA your changes
I've added some tests to ensure the value is set correctly based on several different string values.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by nrgraham23** [comment]
A related PR is here: https://github.com/DataDog/helm-charts/pull/579/files

File: pkg/clusteragent/admission/controllers/webhook/controller_v1.go [hunk 1]
```diff
@@ -242,3 +242,14 @@ func (c *ControllerV1) getWebhookSkeleton(nameSuffix, path string) admiv1.Mutati
 
 	return webhook
 }
+
+func (c *ControllerV1) getAdmiV1FailurePolicy() admiv1.FailurePolicyType {
+	switch c.config.getFailurePolicy() {
+	case "Ignore":
+		return admiv1.Ignore
+	case "Fail":
+		return admiv1.Fail
```
Comment (ahmed-mez) [inline pkg/clusteragent/admission/controllers/webhook/controller_v1.go:251]: we should support lower case config as well
```suggestion
	case "Ignore", "ignore":
		return admiv1.Ignore
	case "Fail", "fail":
		return admiv1.Fail
```

File: pkg/clusteragent/admission/controllers/webhook/controller_v1beta1.go [hunk 2]
```diff
@@ -242,3 +242,14 @@ func (c *ControllerV1beta1) getWebhookSkeleton(nameSuffix, path string) admiv1be
 
 	return webhook
 }
+
+func (c *ControllerV1beta1) getAdmiV1Beta1FailurePolicy() admiv1beta1.FailurePolicyType {
+	switch c.config.getFailurePolicy() {
+	case "Ignore":
+		return admiv1beta1.Ignore
+	case "Fail":
+		return admiv1beta1.Fail
```
Comment (ahmed-mez) [inline pkg/clusteragent/admission/controllers/webhook/controller_v1beta1.go:251]:
```suggestion
	case "Ignore", "ignore":
		return admiv1beta1.Ignore
	case "Fail", "fail":
		return admiv1beta1.Fail
```

Please add a test case for lower-case config 🙇

File: pkg/clusteragent/admission/controllers/webhook/controller_v1.go (hunk 1 above)
Comment (ahmed-mez) [reply pkg/clusteragent/admission/controllers/webhook/controller_v1.go:251]: Please add a test case for lower-case config 🙇

**Review by ahmed-mez — COMMENTED** [review]
Thank you @nrgraham23 for the contribution!

Added a minor comment about supporting lowercase config, but the PR looks good overall!

- Could you document the new config field in [this file](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L2296-L2309)? 
- Could you also add a release note in `releasenotes-dca/notes`? You can use the `reno` tool documented [here](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno).

Thanks!

File: pkg/clusteragent/admission/controllers/webhook/controller_v1beta1.go [hunk 3]
```diff
@@ -242,3 +242,14 @@ func (c *ControllerV1beta1) getWebhookSkeleton(nameSuffix, path string) admiv1be
...
+	default:
```
Comment (ahmed-mez) [inline pkg/clusteragent/admission/controllers/webhook/controller_v1beta1.go:252]: let's add a warning log here

File: pkg/clusteragent/admission/controllers/webhook/controller_v1.go (hunk 1 above)
Comment (nrgraham23) [reply pkg/clusteragent/admission/controllers/webhook/controller_v1.go]: I added the requested change, but I wonder, would it be better to simply lowercase the value and ignore case all together?

File: pkg/clusteragent/admission/controllers/webhook/controller_v1.go [hunk 4]
```diff
@@ -242,3 +242,14 @@ func (c *ControllerV1) getWebhookSkeleton(nameSuffix, path string) admiv1.Mutati
...
+	default:
```
[the remark this answers is not in the document]
Comment (nrgraham23) [reply pkg/clusteragent/admission/controllers/webhook/controller_v1.go:252]: Good idea, added locally, will push soon.

File: pkg/clusteragent/admission/controllers/webhook/controller_v1.go (hunk 1 above)
Comment (ahmed-mez) [reply pkg/clusteragent/admission/controllers/webhook/controller_v1.go]: it would cover more cases yes, thanks 👍

**Review by ahmed-mez — APPROVED** [review]
The CLA needs to be signed https://github.com/DataDog/datadog-agent/pull/11432#issuecomment-1076783749

LGTM otherwise, thank you!

**Comment by nrgraham23** [comment]
Thanks!  Just getting permission on my side to sign that, should be soon.

**Review by cswatt — COMMENTED** [review]
no docs review required

**Review by djmitche — APPROVED** [review]
pkg/config looks good

**Comment by ahmed-mez** [comment]
hey @nrgraham23 ! It would be great we got this merged this week, otherwise we couldn't include it in Cluster Agent v1.20. (The code freeze is on Friday).

**Comment by ahmed-mez** [comment]
Thank you @nrgraham23 ! It's not clear to me why Circleci is stuck and I wasn't able to trigger a new. pipeline, could you please just rebase your branch and push it? just to make sure nothing is broken. Happy to merge it afterwards.
