### PR TITLE
Make the docker entrypoint script honor DD_CRI_SOCKET_PATH

### LINKED ISSUE #21223: [stable/datadog] Docker integration broken when running in Kubernetes
**Describe the bug**
After upgraded to version 2.0.1 of the Datadog chart, container stats are no longer reporting to Datadog. You can view the issue in this screenshot. All the containers for one of our k8s clusters stopped reporting to Datadog.

Screen Shot 2020-03-03 at 11 31 33 AM

**Version of Helm and Kubernetes**:
Helm Version: 3.0.3
Kubernetes Version: 1.15.9

**Which chart**:
stable/datadog

**What happened**:
After upgrading to version 2.0.1 of the chart, Docker statistics stopped reporting to Datadog.

**What you expected to happen**:
The Docker statistics to continue reporting to Datadog.

**How to reproduce it** (as minimally and precisely as possible):
Upgrade to version 2.0.0 or greater of the Datadog chart.

**Anything else we need to know**:
After doing some investigation, it looks like criSocketPath is now prepended with `/host/` by the chart. https://github.com/helm/charts/blob/1388bd56630f4f85ebfee0c090f6b31b02b7b606/stable/datadog/templates/container-agent.yaml#L90

When the Datadog init runs, it looks for the socket in `/var/run/` (without the prefix `/host/`). This causes it to load the wrong config file (datadog-kubernetes.yaml instead of datadog-k8s-docker.yaml). https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/50-kubernetes.sh#L10

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Make the docker entrypoint script honor `DD_CRI_SOCKET_PATH`

### Motivation

In order to fix an issue when the docker daemon is restarted while
a containerized agent is connected to it, the docker socket is now
mounted in a different path.

This change was effective in the Helm chart v2.

We must now ensure that the `DD_CRI_SOCKET_PATH` parameter is honored everywhere.

### Additional Notes

Fixes helm/charts#21223

### CODE REVIEW

**Comment by vboulineau** [comment]
Does it work override this:
https://github.com/DataDog/integrations-core/blob/master/docker_daemon/datadog_checks/docker_daemon/data/conf.yaml.example#L67

For the Docker check to run correctly?

File: Dockerfiles/agent/entrypoint/50-kubernetes.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@ fi
 # Set a default config for Kubernetes if found
 # Don't override /etc/datadog-agent/datadog.yaml if it exists
 if [[ ! -e /etc/datadog-agent/datadog.yaml ]]; then
-    if [[ -e /var/run/docker.sock ]]; then
+    if [[ -S /var/run/docker.sock ]] || ( [[ "$DD_CRI_SOCKET_PATH" =~ docker\.sock ]] && [[ -S "$DD_CRI_SOCKET PATH" ]] ); then
```
Comment (vboulineau) [inline Dockerfiles/agent/entrypoint/50-kubernetes.sh]: You miss an `_` in the last `$DD_CRI_SOCKET PATH`

Comment (L3n41c) [reply Dockerfiles/agent/entrypoint/50-kubernetes.sh]: Fixed!

**Review by vboulineau — APPROVED** [review]

**Review by xornivore — APPROVED** [review]
👍

**Comment by L3n41c** [comment]
> Does it override this:
> https://github.com/DataDog/integrations-core/blob/master/docker_daemon/datadog_checks/docker_daemon/data/conf.yaml.example#L67
> 
> For the Docker check to run correctly?

This check was for agent 5 only. It has been replaced by a go core check which honors `DOCKER_HOST` according to:
https://github.com/DataDog/datadog-agent/blob/dd2257edc2041d419ea41501a9df5319fa8ff7b8/cmd/agent/dist/conf.d/docker.d/conf.yaml.example#L1

The helm chart has been updated to explicitly set `DOCKER_HOST` in helm/charts#21300.
