### PR TITLE
Use a "safe" Sender for core checks

### LINKED ISSUE #7159: Possible issue with tags
**Describe what happened:**

When `tags` are passed to sender (e.g. `sender.Gauge`) they seems to be changed **occasionally** in unexpected way.

**Describe what you expected:**

No missing tags.

**Steps to reproduce the issue:**

### How to reproduce

1/ Change `/etc/datadog-agent/conf.d/network.d/conf.yaml.default` content to:
```
instances:
  - collect_connection_state: false
    tags:
      - foo:bar
```
Having instance tags is necessary to reproduce the issue.

2/ Apply changed to network core check as follow: https://github.com/DataDog/datadog-agent/pull/7156/files

3/ Then build the agent and run network check as follow:

```
$ inv agent.build --python-runtimes 3
$ for i in `seq 1 100`; do echo $i; ./bin/agent/agent check network -l info | grep 'missing tag'; done
```
We are running the `agent check network` multiple times since the issue doesn't happen consistently.

You should see some log lines like this:
```
2021-01-13 10:55:07 UTC | CORE | ERROR | (pkg/collector/corechecks/net/network.go:126 in sendMetric) | missing tag mytag3 in [abc foo:bar mytag1 mytag2]
2021-01-13 10:55:07 UTC | CORE | ERROR | (pkg/collector/corechecks/net/network.go:126 in sendMetric) | missing tag mytag3 in [abc foo:bar mytag1 mytag2]
2021-01-13 10:55:07 UTC | CORE | ERROR | (pkg/collector/corechecks/net/network.go:126 in sendMetric) | missing tag mytag3 in [abc foo:bar mytag1 mytag2]
```

The issue: `mytag3` is not present sometimes.

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Replaces the `aggregator.Sender` used in corechecks with one that automatically clones all tags slices before passing them to the aggreator.

### Motivation

The aggregator takes ownership of the tags slices passed to it, and may modify them in-place.  This has caused issues in the past (e.g., #7159).  It's hard to spot, too.  For example, a trivial-looking modification to a check may result in re-use of a tags slice, e.g.,

```patch
-    s.Gauge("some_metric", metric.Val, hostname, tags)
+    s.Gauge("some_metric.v1", metric.Val, hostname, tags)
+    s.Gauge("some_metric.v2", metric.ValV2, hostname, tags)
```

### Possible Drawbacks / Trade-offs

Copying tags is, naturally, slower.  And it is unnecessary in cases where tags were already handled safely (a new slice created and handed to the sender).  However, to my knowledge none of these checks are so performance-sensitive as to be harmed by that slowness.  And, as shown above, it's easy for a "safe" use of tags to become "unsafe" without being obvious in review.  So I think the cost is worth it for safety.

However, if there are specific high-volume checks that need to skip this clone operation, that's easy -- just call `c.GetRawSender()` instead of `c.GetSender()`.  Please let me know if that applies to any core checks.

### Describe how to test/QA your changes

This PR is written such that it should be easy to verify in review that there are no behavioral changes.  So, please give that a second thought now :)

After that, it's wise to verify that each core check is still producing correct-looking data after this change.  I believe that falls to a number of teams, which I've listed in the team/* labels.  Codeowners suggests:
```
@DataDog/agent-core: pkg/collector/corechecks/checkbase.go
@DataDog/agent-core: pkg/collector/corechecks/containerlifecycle/check.go
@DataDog/agent-integrations: pkg/collector/corechecks/systemd/systemd.go
@DataDog/agent-platform: pkg/collector/corechecks/net/network.go
@DataDog/agent-platform: pkg/collector/corechecks/net/ntp.go
@DataDog/agent-platform: pkg/collector/corechecks/nvidia/jetson/jetson.go
@DataDog/agent-platform: pkg/collector/corechecks/system/cpu/cpu.go
@DataDog/agent-platform: pkg/collector/corechecks/system/cpu/cpu_windows.go
@DataDog/agent-platform: pkg/collector/corechecks/system/cpu/load.go
@DataDog/agent-platform: pkg/collector/corechecks/system/disk/disk_nix.go
@DataDog/agent-platform: pkg/collector/corechecks/system/disk/iostats_nix.go
@DataDog/agent-platform: pkg/collector/corechecks/system/disk/iostats_pdh_windows.go
@DataDog/agent-platform: pkg/collector/corechecks/system/filehandles/file_handles_freebsd.go
@DataDog/agent-platform: pkg/collector/corechecks/system/filehandles/file_handles.go
@DataDog/agent-platform: pkg/collector/corechecks/system/filehandles/file_handles_windows.go
@DataDog/agent-platform: pkg/collector/corechecks/system/memory/memory_nix.go
@DataDog/agent-platform: pkg/collector/corechecks/system/memory/memory_windows.go
@DataDog/agent-platform: pkg/collector/corechecks/system/uptime/uptime.go
@DataDog/agent-platform: pkg/collector/corechecks/system/winkmem/winkmem.go
@DataDog/agent-platform: pkg/collector/corechecks/system/winproc/winproc_windows.go
@DataDog/container-integrations: pkg/collector/corechecks/cluster/helm/helm.go
@DataDog/container-integrations: pkg/collector/corechecks/cluster/ksm/kubernetes_state.go
@DataDog/container-integrations: pkg/collector/corechecks/cluster/kubernetesapiserver/kubernetes_apiserver.go
@DataDog/container-integrations: pkg/collector/corechecks/cluster/orchestrator/orchestrator.go
@DataDog/container-integrations: pkg/collector/corechecks/containers/containerd/check.go
@DataDog/container-integrations: pkg/collector/corechecks/containers/cri/check.go
@DataDog/container-integrations: pkg/collector/corechecks/containers/docker/check.go
@DataDog/container-integrations: pkg/collector/corechecks/containers/generic/check.go
@DataDog/container-integrations: pkg/collector/corechecks/ebpf/oom_kill.go
@DataDog/container-integrations: pkg/collector/corechecks/ebpf/tcp_queue_length.go
@DataDog/infrastructure-integrations: pkg/collector/corechecks/snmp/snmp.go
```

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

Fixes #7159.

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Review by AlexandreYang — APPROVED** [review]
Thanks @djmitche !

I created this follow-up PR specific to SNMP corecheck: https://github.com/DataDog/datadog-agent/pull/11137

File: pkg/collector/corechecks/safesender.go [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+	"github.com/DataDog/datadog-agent/pkg/aggregator"
+	"github.com/DataDog/datadog-agent/pkg/metrics"
+)
+
+// SafeSender implements aggregator.Sender, wrapping the methods to provide
+// some additional safety checks.
+//
+// In particular, the methods taking `tags []string` are wrapped to copy the
+// slice, as the aggregator may modify it in-place.
+type safeSender struct {
```
Comment (remeh) [inline pkg/collector/corechecks/safesender.go:18]: Instead of a new type, should we consider modifying the original `checkSender` to embed a tags preprocessing method:

```go
type checkSender struct {
   ... all existing attributes ...
   preprocTags func([]string) []string
}
```

Where `newCheckSender` would set it to a noop while newSafeSender would set it to your implementation of `cloneTags`, and having this method used everywhere where's it's needed in the `checkSender` implementation:

```go
func (s *checkSender) Counter(metric string, value float64, hostname string, tags []string) {
	s.sendMetricSample(metric, value, hostname, s.preprocTags(tags), metrics.CounterType, false)
}
```

It's an open question (we may have to consider performance impact of an added noop func call) and not a strong opinion, just considering an alternative smaller change.

Comment (djmitche) [reply pkg/collector/corechecks/safesender.go:18]: That's a good suggestion, but separates the component that has the concern (core checks) from the component addressing the concern (aggregator), and means that anything using the aggregator must bear the costs (perf, complexity) while only one component gets the benefits.

Comment (remeh) [reply pkg/collector/corechecks/safesender.go:18]: You're absolutely right.

**Review by vickenty — APPROVED** [review]

**Comment by djmitche** [comment]
I'll update the KSM checks to use a raw sender, since they are already using dedicated tags slices, with no need to copy.

The container checks are passing the same `tags` slice to dozens of `Gauge` calls, so they can't do much better than the safe sender.

**Review by olivielpeau — APPROVED** [review]
Thanks! Would be good to confirm with @DataDog/container-integrations that there are no other high-volume container-related checks that could use the `RawSender` because they already duplicate tag slices.

Not directly related to the change that this PR does, and not a blocker to merge, but do you have a sense of the cost of duplicating these tag slices for the high-volumes checks (say, a check that can submit 10k points/sec, such as the `kubernetes_state_core` check, with quite a few tags per point)? To try to get a sense of whether we should put some effort into implementing a solution that doesn't require duplicating slices.

**Comment by djmitche** [comment]
This precisely matches what DSD does now: inputs are parsed into a [freshly-allocated slice of strings](https://github.com/DataDog/datadog-agent/blob/main/pkg/dogstatsd/parse.go#L81-L86), then that slice is hashed and later dropped if it corresponds to an existing context.  So in principle this isn't likely to be an issue.

However, it may represent a change in behavior for such high-volume agents.  It will add about 10k/s allocations to those agents, mostly increasing GC churn rate and not InUse.  As we've seen, coupled with other memory-use patterns that could lead to OOMs.

That said, I'm not sure there's an alternative, without major changes to the aggregator that would cause performance problems for DSD.

**Review by mfpierre — APPROVED** [review]

**Review by ofek — APPROVED** [review]

**Comment by djmitche** [comment]
I'm going to merge this without @DataDog/container-integrations -- they're listed as QA anyway, so will get a chance to look at that time.

**Comment by djmitche** [comment]
(I'll rebase first to retry the intermittents)

**Review by vboulineau — APPROVED** [review]

**Comment by vboulineau** [comment]
We'll watch the other container checks but it should be okay
