### PR TITLE
try to improve upstart detection

### LINKED ISSUE #677: Installing Beta 6 on Ubuntu 16.04 -> start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
**Output of the info page (if this is a bug)**
```
....
gpg: Total number processed: 1
gpg:              unchanged: 1
Executing: /tmp/tmp.yf3mjDjrXk/gpg.1.sh --recv-keys
--keyserver
hkp://keyserver.ubuntu.com:80
382E94DE
gpg: requesting key 382E94DE from hkp server keyserver.ubuntu.com
gpg: key 382E94DE: "Datadog, Inc <package@datadoghq.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

* Installing the Datadog Agent package

Ign:1 https://apt.datadoghq.com beta InRelease
Hit:2 https://apt.datadoghq.com beta Release
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
datadog-agent is already the newest version (1:6.0.0~beta.1-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Refreshing symlink...


* Keeping old datadog.yaml configuration file

* Starting the Agent...

start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```

**Describe what happened:**
Following these instructions to try out the datadog agent beta 6
https://github.com/DataDog/datadog-agent/tree/master/docs/beta

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by masci**
### What does this PR do?

Improves Upstart detection in the installation script

### Motivation

Detection fails if a system running systemd has the upstart package installed (even if not used as the init system).

Fixes #677

### CODE REVIEW

File: cmd/agent/install_script.sh [hunk 1]
```diff
@@ -235,8 +235,8 @@ fi
 restart_cmd="$sudo_cmd systemctl restart datadog-agent.service"
 stop_instructions="$sudo_cmd systemctl stop datadog-agent"
 start_instructions="$sudo_cmd systemctl start datadog-agent"
-# Upstart
-if command -v start >/dev/null 2>&1; then
+# Try to detect Upstart, this works most of the times but still a best effort
+if [[ `/sbin/init --version` =~ upstart ]]; then
```
Comment (truthbk) [inline cmd/agent/install_script.sh]: I'm not sure if the version is printed to `stdout` or `stderr`, but on `systemd` that'll print a nasty (albeit innocuous) message... Wondering if `/sbin/init --version 2>/dev/null` might work better (only if the output of `--version` goes to stdout)?

Comment (truthbk) [reply cmd/agent/install_script.sh]: Also `[[ ... ]]` is a bashism... It's not a huge deal as this is indeed a bash script, but we tried to keep away from them in the rest of the script I believe.

**Review by truthbk — COMMENTED** [review]
Looks like a pretty sane approach... I'm pretty sure this works as is, but I added some feedback.

File: cmd/agent/install_script.sh (hunk 1 above)
Comment (masci) [reply cmd/agent/install_script.sh]: even worse, it uses regexes, didn't think about this I might need to reconsider

**Review by truthbk — APPROVED** [review]
Let's merge!
