### PR TITLE
[corechecks/ksm] Support HPA v2beta2 again

### LINKED ISSUE #17843: [BUG] Missing HPA metrics after upgrading agent
**Agent Environment**

Agent: `7.44.1`
DCA: `7.44.1`
Helm release: `3.29.3`

**Describe what happened:**
After upgrading from `7.43.1` to `7.44.1` all metrics related to HPA disappear in clusters running Kubernetes `1.21+` version. But these metrics keep working on clusters running Kubernetes `1.24+`:  

DCA logs:
```bash
2023-06-26 20:33:19 UTC | CLUSTER | ERROR | (apimachinery@v0.23.15/pkg/util/runtime/runtime.go:108 in HandleError) | pkg/mod/k8s.io/client-go@v0.23.15/tools/cache/reflector.go:167: Failed to watch *v2.HorizontalPodAutoscaler: failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource
2023-06-26 20:33:19 UTC | CLUSTER | WARN | (client-go@v0.23.15/tools/cache/reflector.go:324 in func1) | pkg/mod/k8s.io/client-go@v0.23.15/tools/cache/reflector.go:167: failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource
```

Also, we've upgraded de Agent to `7.45.0` but this doesn't solve the problem.

**Describe what you expected:**
All metrics working as well. 

**Steps to reproduce the issue:**
- Running on Kubernetes `1.21+`, just upgrade to `7.44.1` or `7.45.0`.

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes Clusters running `1.21+` and `1.24+`
kOps versions: `1.22.5` and `1.25.3`

### PR DESCRIPTION
**Pull request by davidor**
### What does this PR do?

Fixes the KSM check to support HPA v2beta2 again.

Support for HPA v2beta2 was broken in agent v7.44 when the kube-state-metrics dependency was upgraded (https://github.com/DataDog/datadog-agent/pull/15623)

The old kube-state-metrics version that we used only supported HPA v2beta2, so we added some custom code to also support HPA v2. The kube-state-metrics version that we're using now only support v2, so this time we need to add some custom code to support HPA v2beta2.

Fixes https://github.com/DataDog/datadog-agent/issues/17843

### Describe how to test/QA your changes

Deploy the agent with the kubernetes state metrics check enabled. Deploy an HPA. Verify that the `kubernetes_state.hpa.*` metrics are reported both in a recent version of kubernetes (>= 1.23) with HPA v2 and an older version of kubernetes (< 1.23) with HPA v2beta2.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

File: pkg/collector/corechecks/cluster/ksm/kubernetes_state.go [hunk 1]
```diff
@@ -431,11 +431,8 @@ func manageResourcesReplacement(c *apiserver.APIClient, factories []customresour
 		"policy/v1": {
 			"PodDisruptionBudget": customresources.NewPodDisruptionBudgetV1Beta1Factory,
 		},
-
-		// support for newer k8s versions where the newer resources are
-		// not yet supported by KSM
-		"autoscaling/v2beta2": {
-			"HorizontalPodAutoscaler": customresources.NewHorizontalPodAutoscalerV2Factory,
+		"autoscaling/v2": {
+			"HorizontalPodAutoscaler": customresources.NewHorizontalPodAutoscalerV2Beta2Factory,
```
Comment (clamoriniere) [inline pkg/collector/corechecks/cluster/ksm/kubernetes_state.go:435]: should we also support v2beta1 ? and v1?

**Review by clamoriniere — APPROVED** [review]

File: releasenotes-dca/ksm-support-hpa-v2beta2-e745b1d2519a7d6c.yaml [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+# CHANGELOG.rst is rendered. So the text needs to be worded so that
+# it does not depend on any information only available in another
+# section. This may mean repeating some details, but each section
+# must be readable independently of the other.
+#
+# Each section note must be formatted as reStructuredText.
+---
+fixes:
+  - |
+    Fixes the KSM check to support HPA v2beta2 again. This stopped working in agent v7.44.0.
```
Comment (brett0000FF) [inline releasenotes-dca/ksm-support-hpa-v2beta2-e745b1d2519a7d6c.yaml:11]:
```suggestion
    Fixes the KSM check to support HPA v2beta2 again. This stopped working in Agent v7.44.0.
```

File: releasenotes/notes/ksm-support-hpa-v2beta2-e745b1d2519a7d6c.yaml [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+# CHANGELOG.rst is rendered. So the text needs to be worded so that
+# it does not depend on any information only available in another
+# section. This may mean repeating some details, but each section
+# must be readable independently of the other.
+#
+# Each section note must be formatted as reStructuredText.
+---
+fixes:
+  - |
+    Fixes the KSM check to support HPA v2beta2 again. This stopped working in agent v7.44.0.
```
Comment (brett0000FF) [inline releasenotes/notes/ksm-support-hpa-v2beta2-e745b1d2519a7d6c.yaml:11]:
```suggestion
    Fixes the KSM check to support HPA v2beta2 again. This stopped working in Agent v7.44.0.
```

**Review by brett0000FF — APPROVED** [review]
LGTM. Just two small capitalization suggestions for "Agent".
