### PR TITLE
Fix cmd port on some commands

### LINKED ISSUE #2904: configcheck command doesn't use cmd_port value in config to query agent
**Describe what happened:**
The `configcheck` command doesn't seem to be picking up the `cmd_port` in the agent configs if changed to a custom port. Running `configcheck` with the `cmd_port` set to a port other than `5001` returns:

```
Failed to query the agent (running?): Get https://localhost:5001/agent/config-check: dial tcp [::1]:5001: getsockopt: connection refused
Error: unexpected end of JSON input
Usage:
  agent configcheck [flags]

Flags:
  -h, --help      help for configcheck
  -v, --verbose   print additional debug info

Global Flags:
  -c, --cfgpath string   path to directory containing datadog.yaml
  -n, --no-color         disable color output
```

I ran `datadog-agent` status, and confirmed that the agent is up and running.

https://github.com/DataDog/datadog-agent/blob/03047b0354f25a3bd764b47f53b7e36fdb1bd9ee/pkg/flare/config_check.go#L23

**Describe what you expected:**
`configcheck` should query the agent on the configured `cmd_port` set in `datadog.yaml`

**Steps to reproduce the issue:**
1. Change `cmd_port` in `datadog.yaml` to a port other than the default of `5001`
2. Start the agent
3. Run `datadog-agent configcheck`

**Additional environment details (Operating System, Cloud provider, etc):**
Tested on EC2 instance running Amazon Linux and also on my machine locally running macOS Mojave

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Some command URLs were set before the configuration was parsed

### Motivation

Fix #2904 (which was introduced by https://github.com/DataDog/datadog-agent/pull/1479)

### CODE REVIEW

File: pkg/flare/config_check.go [hunk 1]
```diff
@@ -20,7 +20,7 @@ import (
 )
 
 // ConfigCheckURL contains the Agent API endpoint URL exposing the loaded checks
-var ConfigCheckURL = fmt.Sprintf("https://localhost:%v/agent/config-check", config.Datadog.GetInt("cmd_port"))
+var ConfigCheckURL string
```
Comment (olivielpeau) [inline pkg/flare/config_check.go]: let's remove this var as well?

(seems to be used in `pkg/flare/archive_test.go`, but I assume the test could be updated by simply setting `cmd_port`)

**Review by olivielpeau — COMMENTED** [review]
Thanks for fixing this 🙇  left a comment

File: pkg/flare/config_check.go (hunk 1 above)
Comment (mfpierre) [reply pkg/flare/config_check.go]: @olivielpeau the test is done using `httptest` (https://golang.org/pkg/net/http/httptest/)  is it possible to have a custom port and url with this?

Comment (mfpierre) [reply pkg/flare/config_check.go]: Not sure if `httptest` is always on `localhost` but parsing the port from the URL seems to work 🤔

Comment (mfpierre) [reply pkg/flare/config_check.go]: In fact, I had to add it back because it was also used for to change the config check URL for the cluster agent (after rebase, I forgot about this) but I made it private

**Review by xvello — APPROVED** [review]
