### PR TITLE
make series payload max size configurable, better defaults

### LINKED ISSUE #3736: [Potential release blocker] Reduce new stream serialization maxUncompressedSize to a sane number
**Output of the info page (if this is a bug)**

**Describe what happened:**
With the latest version release 6.11 release, the [stream serialization feature](https://github.com/DataDog/datadog-agent/pull/2665) was enabled by default.
This will make most of the time big payloads to have a size of [~45Mb](https://github.com/DataDog/datadog-agent/blob/a97fc8b14932a10f7dff2501286853a061e025ad/pkg/serializer/jsonstream/compressor.go#L49).
As customers update their agent, this bumps the default average size of a payload to somewhere around there especially for customers on kubernetes which usually contains a lot more data.

This is pretty memory-intensive on the edge as we expect payloads that big to usually be outliers. A more wide adoption of that new default will likely have negative impact on the reliability of the pipeline as a whole.

It would be good to set a saner default (2Mb or 4Mb would be perfect, we could probably live with something up to 16Mb)

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by arbll**
### What does this PR do?

- Make the `maxPayloadSize` and `maxUncompressedSize` values of the payload compressor configurable
- Set the default of `maxUncompressedSize` to 4MB

### Motivation

Fixes https://github.com/DataDog/datadog-agent/issues/3736.

### CODE REVIEW

File: pkg/serializer/jsonstream/compressor.go [hunk 1]
```diff
@@ -44,9 +46,8 @@ func init() {
 
 // the backend accepts payloads up to 3MB/50MB, but being conservative is okay
 var (
-	megaByte            = 1024 * 1024
-	maxPayloadSize      = 2*megaByte + megaByte/2 // `2.5*megaByte` won't work with strong typing
-	maxUncompressedSize = 45 * megaByte
+	maxPayloadSize      = config.Datadog.GetInt("serializer_max_payload_size")
```
Comment (sunhay) [inline pkg/serializer/jsonstream/compressor.go]: Is the config guaranteed to be parsed this early that we can use it in a global assignment? This might just always return the default.

Comment (arbll) [reply pkg/serializer/jsonstream/compressor.go]: You're right, moving this at the compressor creation

File: pkg/serializer/jsonstream/compressor.go [hunk 2]
```diff
@@ -44,10 +45,7 @@ func init() {
 
 // the backend accepts payloads up to 3MB/50MB, but being conservative is okay
```
Comment (olivielpeau) [inline pkg/serializer/jsonstream/compressor.go]: move this comment closer to where the vars are now defined

File: pkg/config/config.go [hunk 3]
```diff
@@ -185,6 +187,9 @@ func initConfig(config Config) {
 	config.BindEnvAndSetDefault("histogram_percentiles", []string{"0.95"})
 	// Serializer
 	config.BindEnvAndSetDefault("enable_stream_payload_serialization", true)
+	// Warning: do not change the two following values. Your metrics will get dropped by Datadog's intake.
```
Comment (olivielpeau) [inline pkg/config/config.go]:
```suggestion
	// Warning: do not change the two following values. Your payloads will get dropped by Datadog's intake.
```

**Review by olivielpeau — COMMENTED** [review]
couple of nits, other than that LGTM

File: pkg/serializer/jsonstream/compressor.go [hunk 4]
```diff
@@ -69,15 +66,23 @@ type compressor struct {
 	repacks             int    // numbers of time we had to pack this payload
 	maxUnzippedItemSize int
 	maxZippedItemSize   int
+	maxPayloadSize      int
+	maxUncompressedSize int
```
Comment (olivielpeau) [inline pkg/serializer/jsonstream/compressor.go]: is it still needed to define these as package-level vars?

File: pkg/serializer/jsonstream/compressor.go [hunk 5]
```diff
@@ -69,15 +66,23 @@ type compressor struct {
...
 }
 
 func newCompressor(input, output *bytes.Buffer, header, footer []byte) (*compressor, error) {
+	// the backend accepts payloads up to 3MB compressed / 50MB uncompressed but
+	// prefers small uncompressed payloads of ~4MB
+	maxPayloadSize := config.Datadog.GetInt("serializer_max_payload_size")
+	maxUncompressedSize := config.Datadog.GetInt("serializer_max_uncompressed_payload_size")
```
Comment (olivielpeau) [inline pkg/serializer/jsonstream/compressor.go]: we're probably not in a hot loop, but config `get`s are quite slow. If you have benchmarks confirming this doesn't slow anything down you can disregard.

Later, could be nice to  make these 2 config params arguments of `newCompressor`, would probably simplify the tests as well

**Review by olivielpeau — APPROVED** [review]
couple of comments, feel free to merge anyway

File: pkg/serializer/jsonstream/compressor.go (hunk 5 above)
Comment (arbll) [reply pkg/serializer/jsonstream/compressor.go]: It's not a hot path, we create one compressor per payload.

File: pkg/serializer/jsonstream/compressor.go (hunk 4 above)
Comment (arbll) [reply pkg/serializer/jsonstream/compressor.go]: It's now a field of compressor, github makes it confusing ;)

Comment (arbll) [reply pkg/serializer/jsonstream/compressor.go]: It's now a field of compressor, github is lying to you ;)

Comment (olivielpeau) [reply pkg/serializer/jsonstream/compressor.go]: wow you're right, the diff threw me off 😮
