### PR TITLE
[KSM] Add `timeZone` support for `CronJob`

### LINKED ISSUE #36975: Kubernetes CronJob with timeZone are detected in error with kubernetes_state.cronjob.on_schedule_check
**Agent Environment**

agent 7.63.3

**Describe what happened:**

I setup an alert based on the `kubernetes_state.cronjob.on_schedule_check` to detect missed Cronjob schedules.

Some K8s cronjobs are setup with the Cronjob spec `timeZone` parameter.

Example:

```yaml
  schedule: 30 8 * * 1-6
  timeZone: Europe/Paris
```

With this configuration, the monitor based on this check is in error from 10:30 (UTC+2) even if the job executed at exactly 8:30 (UTC+2)

**Describe what you expected:**

No alert

**Steps to reproduce the issue:**

- Create a cronjob with a schedule based on a non UTC timeZone
- Create a monitor based on the  `kubernetes_state.cronjob.on_schedule_check` 
- Wait for job scheduled execution time

**Additional environment details (Operating System, Cloud provider, etc):**

EKS

**Analysis:**

`kube_cronjob_next_schedule_time` does not take Cronjob spec timeZone parameter into account.

https://github.com/DataDog/datadog-agent/blob/4b274f2259e53f5c0d3ac2e9d5c5867c6cee2be7/pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go#L237

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Properly take into account the `timeZone` field of the `CronJob` objects in the `kubernetes_state.cronjob.on_schedule_check` service check.

### Motivation

* Fix #36975

### Additional Notes

This change is mostly a backport of upstream changes.
Clone [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics) and run:
```console
$ git diff remotes/upstream/release-2.4 remotes/upstream/release-2.15 internal/store/cronjob.go
```

### CODE REVIEW

**Review by sblumenthal — APPROVED** [review]

File: pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go [hunk 1]
```diff
@@ -179,6 +184,28 @@ func (f *cronjobv1beta1Factory) MetricFamilyGenerators() []generator.FamilyGener
 				}
 			}),
 		),
+		*generator.NewFamilyGeneratorWithStability(
+			"kube_cronjob_status_last_successful_time",
+			"LastSuccessfulTime keeps information of when was the last time the job was completed successfully.",
```
Comment (janine-c) [inline pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go:189]:
```suggestion
			"LastSuccessfulTime indicates the last time the job was completed successfully.",
```

**Review by janine-c — APPROVED** [review]

File: pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go (hunk 1 above)
Comment (L3n41c) [reply pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go:189]: This is in fact not a piece of code that we wrote, but something that has been copied from a 3rd party project:
https://github.com/kubernetes/kube-state-metrics/blob/4a585c91beffdbd1378833ce5f102b401e7e57c5/internal/store/cronjob.go#L177
Even if that’s not perfect, I’d rather try to avoid diverging from the upstream project if not needed.

Comment (janine-c) [reply pkg/collector/corechecks/cluster/ksm/customresources/cronjob.go:189]: Ah yeah, that's totally fine!
