### PR TITLE
[clusterchecks/dispatcher_configs] Fix panic. Check if node exists before accessing node.name

### LINKED ISSUE #17403: [BUG] nil pointer dereference in "pkg/clusteragent/clusterchecks".removeConfig
**Agent Environment**

AWS EKS 1.23
```
# agent version
Cluster Agent 7.44.1 - Commit: 299bdcd - Serialization version: v5.0.76 - Go version: go1.19.8
```

**Describe what happened:**
Agent crashes with the following stack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x208c53a]

goroutine 517 [running]:
github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks.(*dispatcher).removeConfig(0xc001e84080, {0xc00306a3a0, 0x10})
    /go/src/github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks/dispatcher_configs.go:99 +0x23a
github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks.(*dispatcher).remove(_, {{0xc0018f0180, 0x16}, {0xc000982978, 0x1, 0x1}, {0xc001885968, 0x3, 0x8}, {0x0, ...}, ...})
    /go/src/github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks/dispatcher_main.go:149 +0xee
github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks.(*dispatcher).Unschedule(0xc0023fb7f8?, {0xc002759600?, 0x1, 0x1?})
    /go/src/github.com/DataDog/datadog-agent/pkg/clusteragent/clusterchecks/dispatcher_main.go:120 +0x4e5
github.com/DataDog/datadog-agent/pkg/autodiscovery/scheduler.(*MetaScheduler).Unschedule(0xc000e14eb8, {0xc002759600?, 0x1, 0x1})
    /go/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/scheduler/meta.go:94 +0x131
github.com/DataDog/datadog-agent/pkg/autodiscovery.(*AutoConfig).applyChanges(0xc0014977c0, {{0x0, 0x0, 0x0}, {0xc002759600, 0x1, 0x1}})
    /go/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/autoconfig.go:452 +0x3e5
github.com/DataDog/datadog-agent/pkg/autodiscovery.(*AutoConfig).processDelService(0xc0014977c0, {0x3bd4230, 0xc001e1b080}, {0x3be8ac0?, 0xc0000cc7d0?})
    /go/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/autoconfig.go:427 +0x165
github.com/DataDog/datadog-agent/pkg/autodiscovery.(*AutoConfig).serviceListening(0xc0014977c0)
    /go/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/autoconfig.go:114 +0x29a
created by github.com/DataDog/datadog-agent/pkg/autodiscovery.NewAutoConfig
    /go/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/autoconfig.go:69 +0x5b
```

**Describe what you expected:**
Agent to not crash.

**Steps to reproduce the issue:**
Unsure. Seems to have been happening sporadically for about a week now. Not sure what changed which might have started this. We've been running the same agent for about 2 weeks, but only seeing crashes start about a week ago.

Help in collecting additional information is would be useful.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.23 & Bottlerocket OS

### PR DESCRIPTION
**Pull request by davidor**
### What does this PR do?

Closes https://github.com/DataDog/datadog-agent/issues/17403

Fixes a panic in the Cluster Agent that happens when trying to unschedule a config that has not been assigned to any runner.

The second commit includes a small cleanup in the function where the panic occurs.

### Describe how to test/QA your changes

- Deploy the Agent on Kubernetes and with cluster check runners enabled. Set the number of replicas for the runners to 0 so cluster checks will not get assigned to any runner. You can use this config when deploying with the Helm chart:
```yaml
datadog:
  clusterChecks:
    enabled: true
clusterChecksRunner:
  enabled: true
  replicas: 0
```
- Create a cluster check. For example, create a service with an http check like describe here: https://docs.datadoghq.com/containers/cluster_agent/clusterchecks/?tab=helm#example-http-check-on-an-nginx-backed-service
- Run `agent clusterchecks` in the Cluster Agent and verify that the new check appears in the "unassigned" section.
- Delete the service with the cluster check and verify that the Cluster Agent does not crash.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by alai97 — APPROVED** [review]
Release note looks good!

File: pkg/clusteragent/clusterchecks/dispatcher_configs.go [hunk 1]
```diff
@@ -90,29 +90,27 @@ func (d *dispatcher) removeConfig(digest string) {
...
-		if v == digest {
-			configsInfo.Delete(node.name, checkName, string(k), le.JoinLeaderValue)
-			delete(d.store.idToDigest, k)
+	var checkIDToRemove checkid.ID
+	for checkID, checkDigest := range d.store.idToDigest {
+		if checkDigest == digest {
+			checkIDToRemove = checkID
+			delete(d.store.idToDigest, checkIDToRemove)
 		}
 	}
```
Comment (L3n41c) [inline pkg/clusteragent/clusterchecks/dispatcher_configs.go:105]: If there’s only one element in `d.store.idToDigest` for which the value is `digest`, we can break the for loop as soon as we’ve found it.

```suggestion
	var checkIDToRemove checkid.ID
	for checkID, checkDigest := range d.store.idToDigest {
		if checkDigest == digest {
			checkIDToRemove = checkID
			delete(d.store.idToDigest, checkIDToRemove)
			break
		}
	}
```

But if it’s possible to have several matches, `checkIDToRemove` should be a list.

File: pkg/clusteragent/clusterchecks/dispatcher_configs.go [hunk 2]
```diff
@@ -90,29 +90,27 @@ func (d *dispatcher) removeConfig(digest string) {
...
 
 	// Remove from node configs if assigned
 	if found {
 		node.Lock()
+		nodeName := node.name
 		node.removeConfig(digest)
 		node.Unlock()
+		configsInfo.Delete(nodeName, checkName, string(checkIDToRemove), le.JoinLeaderValue)
```
Comment (L3n41c) [inline pkg/clusteragent/clusterchecks/dispatcher_configs.go:113]: Is it worth checking if we found the check id to remove with an `if checkIDToRemove != ""` ?

Comment (davidor) [reply pkg/clusteragent/clusterchecks/dispatcher_configs.go:113]: I'm not sure. I think it should never be empty unless there's a bug somewhere else. Also, there's no harm in calling `Delete` on a Gauge with labels that form a combination that doesn't exist. It will simply do nothing.

File: pkg/clusteragent/clusterchecks/dispatcher_configs.go (hunk 1 above)
Comment (davidor) [reply pkg/clusteragent/clusterchecks/dispatcher_configs.go]: At first I thought there could only be one match, but I was wrong.
In configs with multiple instances each one has a check ID, so this needs to be a list.
I've pushed the fix :+1:

File: pkg/clusteragent/clusterchecks/dispatcher_configs.go (hunk 2 above)
Comment (davidor) [reply pkg/clusteragent/clusterchecks/dispatcher_configs.go]: After the fix mentioned above, the check IDs are now in a list, so it's no longer an issue.

**Review by L3n41c — APPROVED** [review]
